/* Generated by Yosys 0.17+76 (git sha1 035496b50, gcc 9.1.0 -fPIC -Os) */

(* top =  1  *)
(* src = "./rtl/and2/and2.v:7.1-18.10" *)
module and2(a, b, c);
  (* src = "./rtl/and2/and2.v:12.12-12.13" *)
  input a;
  wire a;
  (* src = "./rtl/and2/and2.v:13.12-13.13" *)
  input b;
  wire b;
  (* src = "./rtl/and2/and2.v:14.13-14.14" *)
  output c;
  wire c;
`pragma protect author = "Verific"
`pragma protect author_info = "Verific Corporation"
`pragma protect key_method = "rsa"
`pragma protect data_method = "aes128-cbc"
`pragma protect key_keyowner="Verific"
`pragma protect key_keyname="key1"
`pragma protect key_public_key
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDkRq28uVJ64yGZqOJrWPHJASe54e31P1ULNIw6
wa9KiOcrrvH/rTq7wZ9xK3Y0xwmZjOfh/uf89+gwHBQWGMMMmZpPt6A3jR08oM0RmJpwOL4fAsFB
kcgM7BOLt3gppbHQrZryRxXXkyFIoBSJAYTGuu4pfkOzNH7O0zUNwhfMzwIDAQAB
`pragma protect begin
  assign c = 8'hca >> { b, a, 1'h0 };
  `pragma protect end
endmodule