/* Generated by Yosys 0.17+76 (git sha1 035496b50, gcc 9.1.0 -fPIC -Os) */

(* top =  1  *)
(* src = "./rtl/and2_or2/and2_or2.v:8.1-22.10" *)
module and2_or2(a, b, c, d);
  (* src = "./rtl/and2_or2/and2_or2.v:14.12-14.13" *)
  input a;
  wire a;
  (* src = "./rtl/and2_or2/and2_or2.v:15.12-15.13" *)
  input b;
  wire b;
  (* src = "./rtl/and2_or2/and2_or2.v:16.13-16.14" *)
  output c;
  wire c;
  (* src = "./rtl/and2_or2/and2_or2.v:17.13-17.14" *)
  output d;
  wire d;
  \$lut  \$abc$342$auto$blifparse.cc:515:parse_blif$343  (
    .A({ b, 1'h1, a }),
    .Y(d)
  );
  defparam \$abc$342$auto$blifparse.cc:515:parse_blif$343 .LUT = 8'hca;
  defparam \$abc$342$auto$blifparse.cc:515:parse_blif$343 .WIDTH = 32'h00000003;
  \$lut  \$abc$342$auto$blifparse.cc:515:parse_blif$344  (
    .A({ b, a, 1'h0 }),
    .Y(c)
  );
  defparam \$abc$342$auto$blifparse.cc:515:parse_blif$344 .LUT = 8'hca;
  defparam \$abc$342$auto$blifparse.cc:515:parse_blif$344 .WIDTH = 32'h00000003;
endmodule
