/* Generated by Yosys 0.17+76 (git sha1 035496b50, gcc 9.1.0 -fPIC -Os) */

(* top =  1  *)
(* src = "./rtl/and2_or2/and2_or2.v:8.1-22.10" *)
module and2_or2(a, b, c, d);
  (* src = "./rtl/and2_or2/and2_or2.v:14.12-14.13" *)
  input a;
  wire a;
  (* src = "./rtl/and2_or2/and2_or2.v:15.12-15.13" *)
  input b;
  wire b;
  (* src = "./rtl/and2_or2/and2_or2.v:16.13-16.14" *)
  output c;
  wire c;
  (* src = "./rtl/and2_or2/and2_or2.v:17.13-17.14" *)
  output d;
  wire d;
  \$lut  _0_ (
    .A({ b, 1'h1, a }),
    .Y(d)
  );
  defparam _0_.LUT = 8'hca;
  defparam _0_.WIDTH = 32'd3;
  \$lut  _1_ (
    .A({ b, a, 1'h0 }),
    .Y(c)
  );
  defparam _1_.LUT = 8'hca;
  defparam _1_.WIDTH = 32'd3;
endmodule
