/* Generated by Yosys 0.17+76 (git sha1 035496b50, gcc 9.1.0 -fPIC -Os) */

(* top =  1  *)
(* src = "./rtl/full_adder/full_adder.v:1.1-10.10" *)
module full_adder(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "./rtl/full_adder/full_adder.v:3.7-3.8" *)
  input a;
  wire a;
  (* src = "./rtl/full_adder/full_adder.v:3.9-3.10" *)
  input b;
  wire b;
  (* src = "./rtl/full_adder/full_adder.v:3.11-3.14" *)
  input cin;
  wire cin;
  (* src = "./rtl/full_adder/full_adder.v:4.12-4.16" *)
  output cout;
  wire cout;
  (* src = "./rtl/full_adder/full_adder.v:4.8-4.11" *)
  output sum;
  wire sum;
  \$lut  _08_ (
    .A({ b, 1'h1, a }),
    .Y(_02_)
  );
  defparam _08_.LUT = 8'hca;
  defparam _08_.WIDTH = 32'd3;
  \$lut  _09_ (
    .A(a),
    .Y(_05_)
  );
  defparam _09_.LUT = 2'h1;
  defparam _09_.WIDTH = 32'd1;
  \$lut  _10_ (
    .A({ b, _05_, 1'h1 }),
    .Y(_01_)
  );
  defparam _10_.LUT = 8'hca;
  defparam _10_.WIDTH = 32'd3;
  \$lut  _11_ (
    .A({ _02_, 1'h1, cin }),
    .Y(_03_)
  );
  defparam _11_.LUT = 8'hca;
  defparam _11_.WIDTH = 32'd3;
  \$lut  _12_ (
    .A({ _01_, _04_, cin }),
    .Y(_00_)
  );
  defparam _12_.LUT = 8'hca;
  defparam _12_.WIDTH = 32'd3;
  \$lut  _13_ (
    .A({ _00_, _03_, 1'h0 }),
    .Y(sum)
  );
  defparam _13_.LUT = 8'hca;
  defparam _13_.WIDTH = 32'd3;
  \$lut  _14_ (
    .A(_01_),
    .Y(_06_)
  );
  defparam _14_.LUT = 2'h1;
  defparam _14_.WIDTH = 32'd1;
  \$lut  _15_ (
    .A({ _02_, _07_, 1'h1 }),
    .Y(_04_)
  );
  defparam _15_.LUT = 8'hca;
  defparam _15_.WIDTH = 32'd3;
  \$lut  _16_ (
    .A({ _04_, _06_, 1'h1 }),
    .Y(cout)
  );
  defparam _16_.LUT = 8'hca;
  defparam _16_.WIDTH = 32'd3;
  \$lut  _17_ (
    .A(cin),
    .Y(_07_)
  );
  defparam _17_.LUT = 2'h1;
  defparam _17_.WIDTH = 32'd1;
endmodule
