/* Generated by Yosys 0.17+76 (git sha1 035496b50, gcc 9.1.0 -fPIC -Os) */

(* top =  1  *)
(* src = "./rtl/and2_latch/and2_latch.v:9.1-29.10" *)
module and2_latch(a, b, clk, c, d);
  (* src = "./rtl/and2_latch/and2_latch.v:18.12-18.13" *)
  input a;
  wire a;
  (* src = "./rtl/and2_latch/and2_latch.v:19.12-19.13" *)
  input b;
  wire b;
  (* src = "./rtl/and2_latch/and2_latch.v:20.13-20.14" *)
  output c;
  wire c;
  (* src = "./rtl/and2_latch/and2_latch.v:16.12-16.15" *)
  input clk;
  wire clk;
  (* src = "./rtl/and2_latch/and2_latch.v:21.12-21.13" *)
  output d;
  wire d;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/ffs_map.v:18.12-18.81" *)
  dffsre _0_ (
    .C(clk),
    .D(c),
    .E(1'h1),
    .Q(d),
    .R(1'h1),
    .S(1'h1)
  );
  \$lut  #(
    .LUT(8'hca),
    .WIDTH(32'd3)
  ) _1_ (
    .A({ b, a, 1'h0 }),
    .Y(c)
  );
endmodule
