/* Generated by Yosys 0.17+76 (git sha1 035496b50, gcc 9.1.0 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "./rtl/adder_128/adder_128.v:3.1-12.10" *)
module adder_128(cout, sum, a, b, cin);
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:43.7-43.9" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  (* force_downto = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:47.19-47.20" *)
  wire [129:0] _134_;
  (* force_downto = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:49.21-49.22" *)
  (* unused_bits = "127" *)
  wire [128:0] _135_;
  (* src = "./rtl/adder_128/adder_128.v:8.18-8.19" *)
  input [127:0] a;
  wire [127:0] a;
  (* src = "./rtl/adder_128/adder_128.v:8.21-8.22" *)
  input [127:0] b;
  wire [127:0] b;
  (* src = "./rtl/adder_128/adder_128.v:7.7-7.10" *)
  input cin;
  wire cin;
  (* src = "./rtl/adder_128/adder_128.v:5.8-5.12" *)
  output cout;
  wire cout;
  (* src = "./rtl/adder_128/adder_128.v:6.19-6.22" *)
  output [127:0] sum;
  wire [127:0] sum;
  \$lut  _136_ (
    .A(a[18]),
    .Y(_004_)
  );
  defparam _136_.LUT = 2'h1;
  defparam _136_.WIDTH = 32'd1;
  \$lut  _137_ (
    .A({ b[18], _004_, a[18] }),
    .Y(_135_[18])
  );
  defparam _137_.LUT = 8'hca;
  defparam _137_.WIDTH = 32'd3;
  \$lut  _138_ (
    .A(a[19]),
    .Y(_005_)
  );
  defparam _138_.LUT = 2'h1;
  defparam _138_.WIDTH = 32'd1;
  \$lut  _139_ (
    .A({ b[19], _005_, a[19] }),
    .Y(_135_[19])
  );
  defparam _139_.LUT = 8'hca;
  defparam _139_.WIDTH = 32'd3;
  \$lut  _140_ (
    .A(a[20]),
    .Y(_006_)
  );
  defparam _140_.LUT = 2'h1;
  defparam _140_.WIDTH = 32'd1;
  \$lut  _141_ (
    .A({ b[20], _006_, a[20] }),
    .Y(_135_[20])
  );
  defparam _141_.LUT = 8'hca;
  defparam _141_.WIDTH = 32'd3;
  \$lut  _142_ (
    .A(a[21]),
    .Y(_007_)
  );
  defparam _142_.LUT = 2'h1;
  defparam _142_.WIDTH = 32'd1;
  \$lut  _143_ (
    .A({ b[21], _007_, a[21] }),
    .Y(_135_[21])
  );
  defparam _143_.LUT = 8'hca;
  defparam _143_.WIDTH = 32'd3;
  \$lut  _144_ (
    .A(a[22]),
    .Y(_008_)
  );
  defparam _144_.LUT = 2'h1;
  defparam _144_.WIDTH = 32'd1;
  \$lut  _145_ (
    .A({ b[22], _008_, a[22] }),
    .Y(_135_[22])
  );
  defparam _145_.LUT = 8'hca;
  defparam _145_.WIDTH = 32'd3;
  \$lut  _146_ (
    .A(a[23]),
    .Y(_009_)
  );
  defparam _146_.LUT = 2'h1;
  defparam _146_.WIDTH = 32'd1;
  \$lut  _147_ (
    .A({ b[23], _009_, a[23] }),
    .Y(_135_[23])
  );
  defparam _147_.LUT = 8'hca;
  defparam _147_.WIDTH = 32'd3;
  \$lut  _148_ (
    .A(a[24]),
    .Y(_010_)
  );
  defparam _148_.LUT = 2'h1;
  defparam _148_.WIDTH = 32'd1;
  \$lut  _149_ (
    .A({ b[24], _010_, a[24] }),
    .Y(_135_[24])
  );
  defparam _149_.LUT = 8'hca;
  defparam _149_.WIDTH = 32'd3;
  \$lut  _150_ (
    .A(a[25]),
    .Y(_011_)
  );
  defparam _150_.LUT = 2'h1;
  defparam _150_.WIDTH = 32'd1;
  \$lut  _151_ (
    .A({ b[25], _011_, a[25] }),
    .Y(_135_[25])
  );
  defparam _151_.LUT = 8'hca;
  defparam _151_.WIDTH = 32'd3;
  \$lut  _152_ (
    .A(a[26]),
    .Y(_012_)
  );
  defparam _152_.LUT = 2'h1;
  defparam _152_.WIDTH = 32'd1;
  \$lut  _153_ (
    .A({ b[26], _012_, a[26] }),
    .Y(_135_[26])
  );
  defparam _153_.LUT = 8'hca;
  defparam _153_.WIDTH = 32'd3;
  \$lut  _154_ (
    .A(a[27]),
    .Y(_013_)
  );
  defparam _154_.LUT = 2'h1;
  defparam _154_.WIDTH = 32'd1;
  \$lut  _155_ (
    .A({ b[27], _013_, a[27] }),
    .Y(_135_[27])
  );
  defparam _155_.LUT = 8'hca;
  defparam _155_.WIDTH = 32'd3;
  \$lut  _156_ (
    .A(a[28]),
    .Y(_014_)
  );
  defparam _156_.LUT = 2'h1;
  defparam _156_.WIDTH = 32'd1;
  \$lut  _157_ (
    .A({ b[28], _014_, a[28] }),
    .Y(_135_[28])
  );
  defparam _157_.LUT = 8'hca;
  defparam _157_.WIDTH = 32'd3;
  \$lut  _158_ (
    .A(a[29]),
    .Y(_015_)
  );
  defparam _158_.LUT = 2'h1;
  defparam _158_.WIDTH = 32'd1;
  \$lut  _159_ (
    .A({ b[29], _015_, a[29] }),
    .Y(_135_[29])
  );
  defparam _159_.LUT = 8'hca;
  defparam _159_.WIDTH = 32'd3;
  \$lut  _160_ (
    .A(a[30]),
    .Y(_016_)
  );
  defparam _160_.LUT = 2'h1;
  defparam _160_.WIDTH = 32'd1;
  \$lut  _161_ (
    .A({ b[30], _016_, a[30] }),
    .Y(_135_[30])
  );
  defparam _161_.LUT = 8'hca;
  defparam _161_.WIDTH = 32'd3;
  \$lut  _162_ (
    .A(a[31]),
    .Y(_017_)
  );
  defparam _162_.LUT = 2'h1;
  defparam _162_.WIDTH = 32'd1;
  \$lut  _163_ (
    .A({ b[31], _017_, a[31] }),
    .Y(_135_[31])
  );
  defparam _163_.LUT = 8'hca;
  defparam _163_.WIDTH = 32'd3;
  \$lut  _164_ (
    .A(a[32]),
    .Y(_018_)
  );
  defparam _164_.LUT = 2'h1;
  defparam _164_.WIDTH = 32'd1;
  \$lut  _165_ (
    .A({ b[32], _018_, a[32] }),
    .Y(_135_[32])
  );
  defparam _165_.LUT = 8'hca;
  defparam _165_.WIDTH = 32'd3;
  \$lut  _166_ (
    .A(a[33]),
    .Y(_019_)
  );
  defparam _166_.LUT = 2'h1;
  defparam _166_.WIDTH = 32'd1;
  \$lut  _167_ (
    .A({ b[33], _019_, a[33] }),
    .Y(_135_[33])
  );
  defparam _167_.LUT = 8'hca;
  defparam _167_.WIDTH = 32'd3;
  \$lut  _168_ (
    .A(a[34]),
    .Y(_020_)
  );
  defparam _168_.LUT = 2'h1;
  defparam _168_.WIDTH = 32'd1;
  \$lut  _169_ (
    .A({ b[34], _020_, a[34] }),
    .Y(_135_[34])
  );
  defparam _169_.LUT = 8'hca;
  defparam _169_.WIDTH = 32'd3;
  \$lut  _170_ (
    .A(a[35]),
    .Y(_021_)
  );
  defparam _170_.LUT = 2'h1;
  defparam _170_.WIDTH = 32'd1;
  \$lut  _171_ (
    .A({ b[35], _021_, a[35] }),
    .Y(_135_[35])
  );
  defparam _171_.LUT = 8'hca;
  defparam _171_.WIDTH = 32'd3;
  \$lut  _172_ (
    .A(a[36]),
    .Y(_022_)
  );
  defparam _172_.LUT = 2'h1;
  defparam _172_.WIDTH = 32'd1;
  \$lut  _173_ (
    .A({ b[36], _022_, a[36] }),
    .Y(_135_[36])
  );
  defparam _173_.LUT = 8'hca;
  defparam _173_.WIDTH = 32'd3;
  \$lut  _174_ (
    .A(a[37]),
    .Y(_023_)
  );
  defparam _174_.LUT = 2'h1;
  defparam _174_.WIDTH = 32'd1;
  \$lut  _175_ (
    .A({ b[37], _023_, a[37] }),
    .Y(_135_[37])
  );
  defparam _175_.LUT = 8'hca;
  defparam _175_.WIDTH = 32'd3;
  \$lut  _176_ (
    .A(a[38]),
    .Y(_024_)
  );
  defparam _176_.LUT = 2'h1;
  defparam _176_.WIDTH = 32'd1;
  \$lut  _177_ (
    .A({ b[38], _024_, a[38] }),
    .Y(_135_[38])
  );
  defparam _177_.LUT = 8'hca;
  defparam _177_.WIDTH = 32'd3;
  \$lut  _178_ (
    .A(a[39]),
    .Y(_025_)
  );
  defparam _178_.LUT = 2'h1;
  defparam _178_.WIDTH = 32'd1;
  \$lut  _179_ (
    .A({ b[39], _025_, a[39] }),
    .Y(_135_[39])
  );
  defparam _179_.LUT = 8'hca;
  defparam _179_.WIDTH = 32'd3;
  \$lut  _180_ (
    .A(a[40]),
    .Y(_026_)
  );
  defparam _180_.LUT = 2'h1;
  defparam _180_.WIDTH = 32'd1;
  \$lut  _181_ (
    .A({ b[40], _026_, a[40] }),
    .Y(_135_[40])
  );
  defparam _181_.LUT = 8'hca;
  defparam _181_.WIDTH = 32'd3;
  \$lut  _182_ (
    .A(a[41]),
    .Y(_027_)
  );
  defparam _182_.LUT = 2'h1;
  defparam _182_.WIDTH = 32'd1;
  \$lut  _183_ (
    .A({ b[41], _027_, a[41] }),
    .Y(_135_[41])
  );
  defparam _183_.LUT = 8'hca;
  defparam _183_.WIDTH = 32'd3;
  \$lut  _184_ (
    .A(a[42]),
    .Y(_028_)
  );
  defparam _184_.LUT = 2'h1;
  defparam _184_.WIDTH = 32'd1;
  \$lut  _185_ (
    .A({ b[42], _028_, a[42] }),
    .Y(_135_[42])
  );
  defparam _185_.LUT = 8'hca;
  defparam _185_.WIDTH = 32'd3;
  \$lut  _186_ (
    .A(a[43]),
    .Y(_029_)
  );
  defparam _186_.LUT = 2'h1;
  defparam _186_.WIDTH = 32'd1;
  \$lut  _187_ (
    .A({ b[43], _029_, a[43] }),
    .Y(_135_[43])
  );
  defparam _187_.LUT = 8'hca;
  defparam _187_.WIDTH = 32'd3;
  \$lut  _188_ (
    .A(a[44]),
    .Y(_030_)
  );
  defparam _188_.LUT = 2'h1;
  defparam _188_.WIDTH = 32'd1;
  \$lut  _189_ (
    .A({ b[44], _030_, a[44] }),
    .Y(_135_[44])
  );
  defparam _189_.LUT = 8'hca;
  defparam _189_.WIDTH = 32'd3;
  \$lut  _190_ (
    .A(a[45]),
    .Y(_031_)
  );
  defparam _190_.LUT = 2'h1;
  defparam _190_.WIDTH = 32'd1;
  \$lut  _191_ (
    .A({ b[45], _031_, a[45] }),
    .Y(_135_[45])
  );
  defparam _191_.LUT = 8'hca;
  defparam _191_.WIDTH = 32'd3;
  \$lut  _192_ (
    .A(a[46]),
    .Y(_032_)
  );
  defparam _192_.LUT = 2'h1;
  defparam _192_.WIDTH = 32'd1;
  \$lut  _193_ (
    .A({ b[46], _032_, a[46] }),
    .Y(_135_[46])
  );
  defparam _193_.LUT = 8'hca;
  defparam _193_.WIDTH = 32'd3;
  \$lut  _194_ (
    .A(a[47]),
    .Y(_033_)
  );
  defparam _194_.LUT = 2'h1;
  defparam _194_.WIDTH = 32'd1;
  \$lut  _195_ (
    .A({ b[47], _033_, a[47] }),
    .Y(_135_[47])
  );
  defparam _195_.LUT = 8'hca;
  defparam _195_.WIDTH = 32'd3;
  \$lut  _196_ (
    .A(a[48]),
    .Y(_034_)
  );
  defparam _196_.LUT = 2'h1;
  defparam _196_.WIDTH = 32'd1;
  \$lut  _197_ (
    .A({ b[48], _034_, a[48] }),
    .Y(_135_[48])
  );
  defparam _197_.LUT = 8'hca;
  defparam _197_.WIDTH = 32'd3;
  \$lut  _198_ (
    .A(a[49]),
    .Y(_035_)
  );
  defparam _198_.LUT = 2'h1;
  defparam _198_.WIDTH = 32'd1;
  \$lut  _199_ (
    .A({ b[49], _035_, a[49] }),
    .Y(_135_[49])
  );
  defparam _199_.LUT = 8'hca;
  defparam _199_.WIDTH = 32'd3;
  \$lut  _200_ (
    .A(a[50]),
    .Y(_036_)
  );
  defparam _200_.LUT = 2'h1;
  defparam _200_.WIDTH = 32'd1;
  \$lut  _201_ (
    .A({ b[50], _036_, a[50] }),
    .Y(_135_[50])
  );
  defparam _201_.LUT = 8'hca;
  defparam _201_.WIDTH = 32'd3;
  \$lut  _202_ (
    .A(a[51]),
    .Y(_037_)
  );
  defparam _202_.LUT = 2'h1;
  defparam _202_.WIDTH = 32'd1;
  \$lut  _203_ (
    .A({ b[51], _037_, a[51] }),
    .Y(_135_[51])
  );
  defparam _203_.LUT = 8'hca;
  defparam _203_.WIDTH = 32'd3;
  \$lut  _204_ (
    .A(a[52]),
    .Y(_038_)
  );
  defparam _204_.LUT = 2'h1;
  defparam _204_.WIDTH = 32'd1;
  \$lut  _205_ (
    .A({ b[52], _038_, a[52] }),
    .Y(_135_[52])
  );
  defparam _205_.LUT = 8'hca;
  defparam _205_.WIDTH = 32'd3;
  \$lut  _206_ (
    .A(a[53]),
    .Y(_039_)
  );
  defparam _206_.LUT = 2'h1;
  defparam _206_.WIDTH = 32'd1;
  \$lut  _207_ (
    .A({ b[53], _039_, a[53] }),
    .Y(_135_[53])
  );
  defparam _207_.LUT = 8'hca;
  defparam _207_.WIDTH = 32'd3;
  \$lut  _208_ (
    .A(a[54]),
    .Y(_040_)
  );
  defparam _208_.LUT = 2'h1;
  defparam _208_.WIDTH = 32'd1;
  \$lut  _209_ (
    .A({ b[54], _040_, a[54] }),
    .Y(_135_[54])
  );
  defparam _209_.LUT = 8'hca;
  defparam _209_.WIDTH = 32'd3;
  \$lut  _210_ (
    .A(a[55]),
    .Y(_041_)
  );
  defparam _210_.LUT = 2'h1;
  defparam _210_.WIDTH = 32'd1;
  \$lut  _211_ (
    .A({ b[55], _041_, a[55] }),
    .Y(_135_[55])
  );
  defparam _211_.LUT = 8'hca;
  defparam _211_.WIDTH = 32'd3;
  \$lut  _212_ (
    .A(a[56]),
    .Y(_042_)
  );
  defparam _212_.LUT = 2'h1;
  defparam _212_.WIDTH = 32'd1;
  \$lut  _213_ (
    .A({ b[56], _042_, a[56] }),
    .Y(_135_[56])
  );
  defparam _213_.LUT = 8'hca;
  defparam _213_.WIDTH = 32'd3;
  \$lut  _214_ (
    .A(a[57]),
    .Y(_043_)
  );
  defparam _214_.LUT = 2'h1;
  defparam _214_.WIDTH = 32'd1;
  \$lut  _215_ (
    .A({ b[57], _043_, a[57] }),
    .Y(_135_[57])
  );
  defparam _215_.LUT = 8'hca;
  defparam _215_.WIDTH = 32'd3;
  \$lut  _216_ (
    .A(a[58]),
    .Y(_044_)
  );
  defparam _216_.LUT = 2'h1;
  defparam _216_.WIDTH = 32'd1;
  \$lut  _217_ (
    .A({ b[58], _044_, a[58] }),
    .Y(_135_[58])
  );
  defparam _217_.LUT = 8'hca;
  defparam _217_.WIDTH = 32'd3;
  \$lut  _218_ (
    .A(a[59]),
    .Y(_045_)
  );
  defparam _218_.LUT = 2'h1;
  defparam _218_.WIDTH = 32'd1;
  \$lut  _219_ (
    .A({ b[59], _045_, a[59] }),
    .Y(_135_[59])
  );
  defparam _219_.LUT = 8'hca;
  defparam _219_.WIDTH = 32'd3;
  \$lut  _220_ (
    .A(a[60]),
    .Y(_046_)
  );
  defparam _220_.LUT = 2'h1;
  defparam _220_.WIDTH = 32'd1;
  \$lut  _221_ (
    .A({ b[60], _046_, a[60] }),
    .Y(_135_[60])
  );
  defparam _221_.LUT = 8'hca;
  defparam _221_.WIDTH = 32'd3;
  \$lut  _222_ (
    .A(a[61]),
    .Y(_047_)
  );
  defparam _222_.LUT = 2'h1;
  defparam _222_.WIDTH = 32'd1;
  \$lut  _223_ (
    .A({ b[61], _047_, a[61] }),
    .Y(_135_[61])
  );
  defparam _223_.LUT = 8'hca;
  defparam _223_.WIDTH = 32'd3;
  \$lut  _224_ (
    .A(a[62]),
    .Y(_048_)
  );
  defparam _224_.LUT = 2'h1;
  defparam _224_.WIDTH = 32'd1;
  \$lut  _225_ (
    .A({ b[62], _048_, a[62] }),
    .Y(_135_[62])
  );
  defparam _225_.LUT = 8'hca;
  defparam _225_.WIDTH = 32'd3;
  \$lut  _226_ (
    .A(a[63]),
    .Y(_049_)
  );
  defparam _226_.LUT = 2'h1;
  defparam _226_.WIDTH = 32'd1;
  \$lut  _227_ (
    .A({ b[63], _049_, a[63] }),
    .Y(_135_[63])
  );
  defparam _227_.LUT = 8'hca;
  defparam _227_.WIDTH = 32'd3;
  \$lut  _228_ (
    .A(a[64]),
    .Y(_050_)
  );
  defparam _228_.LUT = 2'h1;
  defparam _228_.WIDTH = 32'd1;
  \$lut  _229_ (
    .A({ b[64], _050_, a[64] }),
    .Y(_135_[64])
  );
  defparam _229_.LUT = 8'hca;
  defparam _229_.WIDTH = 32'd3;
  \$lut  _230_ (
    .A(a[65]),
    .Y(_051_)
  );
  defparam _230_.LUT = 2'h1;
  defparam _230_.WIDTH = 32'd1;
  \$lut  _231_ (
    .A({ b[65], _051_, a[65] }),
    .Y(_135_[65])
  );
  defparam _231_.LUT = 8'hca;
  defparam _231_.WIDTH = 32'd3;
  \$lut  _232_ (
    .A(a[66]),
    .Y(_052_)
  );
  defparam _232_.LUT = 2'h1;
  defparam _232_.WIDTH = 32'd1;
  \$lut  _233_ (
    .A({ b[66], _052_, a[66] }),
    .Y(_135_[66])
  );
  defparam _233_.LUT = 8'hca;
  defparam _233_.WIDTH = 32'd3;
  \$lut  _234_ (
    .A(a[67]),
    .Y(_053_)
  );
  defparam _234_.LUT = 2'h1;
  defparam _234_.WIDTH = 32'd1;
  \$lut  _235_ (
    .A({ b[67], _053_, a[67] }),
    .Y(_135_[67])
  );
  defparam _235_.LUT = 8'hca;
  defparam _235_.WIDTH = 32'd3;
  \$lut  _236_ (
    .A(a[68]),
    .Y(_054_)
  );
  defparam _236_.LUT = 2'h1;
  defparam _236_.WIDTH = 32'd1;
  \$lut  _237_ (
    .A({ b[68], _054_, a[68] }),
    .Y(_135_[68])
  );
  defparam _237_.LUT = 8'hca;
  defparam _237_.WIDTH = 32'd3;
  \$lut  _238_ (
    .A(a[69]),
    .Y(_055_)
  );
  defparam _238_.LUT = 2'h1;
  defparam _238_.WIDTH = 32'd1;
  \$lut  _239_ (
    .A({ b[69], _055_, a[69] }),
    .Y(_135_[69])
  );
  defparam _239_.LUT = 8'hca;
  defparam _239_.WIDTH = 32'd3;
  \$lut  _240_ (
    .A(a[70]),
    .Y(_056_)
  );
  defparam _240_.LUT = 2'h1;
  defparam _240_.WIDTH = 32'd1;
  \$lut  _241_ (
    .A({ b[70], _056_, a[70] }),
    .Y(_135_[70])
  );
  defparam _241_.LUT = 8'hca;
  defparam _241_.WIDTH = 32'd3;
  \$lut  _242_ (
    .A(a[71]),
    .Y(_057_)
  );
  defparam _242_.LUT = 2'h1;
  defparam _242_.WIDTH = 32'd1;
  \$lut  _243_ (
    .A({ b[71], _057_, a[71] }),
    .Y(_135_[71])
  );
  defparam _243_.LUT = 8'hca;
  defparam _243_.WIDTH = 32'd3;
  \$lut  _244_ (
    .A(a[72]),
    .Y(_058_)
  );
  defparam _244_.LUT = 2'h1;
  defparam _244_.WIDTH = 32'd1;
  \$lut  _245_ (
    .A({ b[72], _058_, a[72] }),
    .Y(_135_[72])
  );
  defparam _245_.LUT = 8'hca;
  defparam _245_.WIDTH = 32'd3;
  \$lut  _246_ (
    .A(a[73]),
    .Y(_059_)
  );
  defparam _246_.LUT = 2'h1;
  defparam _246_.WIDTH = 32'd1;
  \$lut  _247_ (
    .A({ b[73], _059_, a[73] }),
    .Y(_135_[73])
  );
  defparam _247_.LUT = 8'hca;
  defparam _247_.WIDTH = 32'd3;
  \$lut  _248_ (
    .A(a[74]),
    .Y(_060_)
  );
  defparam _248_.LUT = 2'h1;
  defparam _248_.WIDTH = 32'd1;
  \$lut  _249_ (
    .A({ b[74], _060_, a[74] }),
    .Y(_135_[74])
  );
  defparam _249_.LUT = 8'hca;
  defparam _249_.WIDTH = 32'd3;
  \$lut  _250_ (
    .A(a[75]),
    .Y(_061_)
  );
  defparam _250_.LUT = 2'h1;
  defparam _250_.WIDTH = 32'd1;
  \$lut  _251_ (
    .A({ b[75], _061_, a[75] }),
    .Y(_135_[75])
  );
  defparam _251_.LUT = 8'hca;
  defparam _251_.WIDTH = 32'd3;
  \$lut  _252_ (
    .A(a[76]),
    .Y(_062_)
  );
  defparam _252_.LUT = 2'h1;
  defparam _252_.WIDTH = 32'd1;
  \$lut  _253_ (
    .A({ b[76], _062_, a[76] }),
    .Y(_135_[76])
  );
  defparam _253_.LUT = 8'hca;
  defparam _253_.WIDTH = 32'd3;
  \$lut  _254_ (
    .A(a[77]),
    .Y(_063_)
  );
  defparam _254_.LUT = 2'h1;
  defparam _254_.WIDTH = 32'd1;
  \$lut  _255_ (
    .A({ b[77], _063_, a[77] }),
    .Y(_135_[77])
  );
  defparam _255_.LUT = 8'hca;
  defparam _255_.WIDTH = 32'd3;
  \$lut  _256_ (
    .A(a[78]),
    .Y(_064_)
  );
  defparam _256_.LUT = 2'h1;
  defparam _256_.WIDTH = 32'd1;
  \$lut  _257_ (
    .A({ b[78], _064_, a[78] }),
    .Y(_135_[78])
  );
  defparam _257_.LUT = 8'hca;
  defparam _257_.WIDTH = 32'd3;
  \$lut  _258_ (
    .A(a[79]),
    .Y(_065_)
  );
  defparam _258_.LUT = 2'h1;
  defparam _258_.WIDTH = 32'd1;
  \$lut  _259_ (
    .A({ b[79], _065_, a[79] }),
    .Y(_135_[79])
  );
  defparam _259_.LUT = 8'hca;
  defparam _259_.WIDTH = 32'd3;
  \$lut  _260_ (
    .A(a[80]),
    .Y(_066_)
  );
  defparam _260_.LUT = 2'h1;
  defparam _260_.WIDTH = 32'd1;
  \$lut  _261_ (
    .A({ b[80], _066_, a[80] }),
    .Y(_135_[80])
  );
  defparam _261_.LUT = 8'hca;
  defparam _261_.WIDTH = 32'd3;
  \$lut  _262_ (
    .A(a[81]),
    .Y(_067_)
  );
  defparam _262_.LUT = 2'h1;
  defparam _262_.WIDTH = 32'd1;
  \$lut  _263_ (
    .A({ b[81], _067_, a[81] }),
    .Y(_135_[81])
  );
  defparam _263_.LUT = 8'hca;
  defparam _263_.WIDTH = 32'd3;
  \$lut  _264_ (
    .A(a[82]),
    .Y(_068_)
  );
  defparam _264_.LUT = 2'h1;
  defparam _264_.WIDTH = 32'd1;
  \$lut  _265_ (
    .A({ b[82], _068_, a[82] }),
    .Y(_135_[82])
  );
  defparam _265_.LUT = 8'hca;
  defparam _265_.WIDTH = 32'd3;
  \$lut  _266_ (
    .A(a[83]),
    .Y(_069_)
  );
  defparam _266_.LUT = 2'h1;
  defparam _266_.WIDTH = 32'd1;
  \$lut  _267_ (
    .A({ b[83], _069_, a[83] }),
    .Y(_135_[83])
  );
  defparam _267_.LUT = 8'hca;
  defparam _267_.WIDTH = 32'd3;
  \$lut  _268_ (
    .A(a[84]),
    .Y(_070_)
  );
  defparam _268_.LUT = 2'h1;
  defparam _268_.WIDTH = 32'd1;
  \$lut  _269_ (
    .A({ b[84], _070_, a[84] }),
    .Y(_135_[84])
  );
  defparam _269_.LUT = 8'hca;
  defparam _269_.WIDTH = 32'd3;
  \$lut  _270_ (
    .A(a[85]),
    .Y(_071_)
  );
  defparam _270_.LUT = 2'h1;
  defparam _270_.WIDTH = 32'd1;
  \$lut  _271_ (
    .A({ b[85], _071_, a[85] }),
    .Y(_135_[85])
  );
  defparam _271_.LUT = 8'hca;
  defparam _271_.WIDTH = 32'd3;
  \$lut  _272_ (
    .A(a[86]),
    .Y(_072_)
  );
  defparam _272_.LUT = 2'h1;
  defparam _272_.WIDTH = 32'd1;
  \$lut  _273_ (
    .A({ b[86], _072_, a[86] }),
    .Y(_135_[86])
  );
  defparam _273_.LUT = 8'hca;
  defparam _273_.WIDTH = 32'd3;
  \$lut  _274_ (
    .A(a[87]),
    .Y(_073_)
  );
  defparam _274_.LUT = 2'h1;
  defparam _274_.WIDTH = 32'd1;
  \$lut  _275_ (
    .A({ b[87], _073_, a[87] }),
    .Y(_135_[87])
  );
  defparam _275_.LUT = 8'hca;
  defparam _275_.WIDTH = 32'd3;
  \$lut  _276_ (
    .A(a[88]),
    .Y(_074_)
  );
  defparam _276_.LUT = 2'h1;
  defparam _276_.WIDTH = 32'd1;
  \$lut  _277_ (
    .A({ b[88], _074_, a[88] }),
    .Y(_135_[88])
  );
  defparam _277_.LUT = 8'hca;
  defparam _277_.WIDTH = 32'd3;
  \$lut  _278_ (
    .A(a[89]),
    .Y(_075_)
  );
  defparam _278_.LUT = 2'h1;
  defparam _278_.WIDTH = 32'd1;
  \$lut  _279_ (
    .A({ b[89], _075_, a[89] }),
    .Y(_135_[89])
  );
  defparam _279_.LUT = 8'hca;
  defparam _279_.WIDTH = 32'd3;
  \$lut  _280_ (
    .A(a[90]),
    .Y(_076_)
  );
  defparam _280_.LUT = 2'h1;
  defparam _280_.WIDTH = 32'd1;
  \$lut  _281_ (
    .A({ b[90], _076_, a[90] }),
    .Y(_135_[90])
  );
  defparam _281_.LUT = 8'hca;
  defparam _281_.WIDTH = 32'd3;
  \$lut  _282_ (
    .A(a[91]),
    .Y(_077_)
  );
  defparam _282_.LUT = 2'h1;
  defparam _282_.WIDTH = 32'd1;
  \$lut  _283_ (
    .A({ b[91], _077_, a[91] }),
    .Y(_135_[91])
  );
  defparam _283_.LUT = 8'hca;
  defparam _283_.WIDTH = 32'd3;
  \$lut  _284_ (
    .A(a[92]),
    .Y(_078_)
  );
  defparam _284_.LUT = 2'h1;
  defparam _284_.WIDTH = 32'd1;
  \$lut  _285_ (
    .A({ b[92], _078_, a[92] }),
    .Y(_135_[92])
  );
  defparam _285_.LUT = 8'hca;
  defparam _285_.WIDTH = 32'd3;
  \$lut  _286_ (
    .A(a[93]),
    .Y(_079_)
  );
  defparam _286_.LUT = 2'h1;
  defparam _286_.WIDTH = 32'd1;
  \$lut  _287_ (
    .A({ b[93], _079_, a[93] }),
    .Y(_135_[93])
  );
  defparam _287_.LUT = 8'hca;
  defparam _287_.WIDTH = 32'd3;
  \$lut  _288_ (
    .A(a[94]),
    .Y(_080_)
  );
  defparam _288_.LUT = 2'h1;
  defparam _288_.WIDTH = 32'd1;
  \$lut  _289_ (
    .A({ b[94], _080_, a[94] }),
    .Y(_135_[94])
  );
  defparam _289_.LUT = 8'hca;
  defparam _289_.WIDTH = 32'd3;
  \$lut  _290_ (
    .A(a[95]),
    .Y(_081_)
  );
  defparam _290_.LUT = 2'h1;
  defparam _290_.WIDTH = 32'd1;
  \$lut  _291_ (
    .A({ b[95], _081_, a[95] }),
    .Y(_135_[95])
  );
  defparam _291_.LUT = 8'hca;
  defparam _291_.WIDTH = 32'd3;
  \$lut  _292_ (
    .A(a[96]),
    .Y(_082_)
  );
  defparam _292_.LUT = 2'h1;
  defparam _292_.WIDTH = 32'd1;
  \$lut  _293_ (
    .A({ b[96], _082_, a[96] }),
    .Y(_135_[96])
  );
  defparam _293_.LUT = 8'hca;
  defparam _293_.WIDTH = 32'd3;
  \$lut  _294_ (
    .A(a[97]),
    .Y(_083_)
  );
  defparam _294_.LUT = 2'h1;
  defparam _294_.WIDTH = 32'd1;
  \$lut  _295_ (
    .A({ b[97], _083_, a[97] }),
    .Y(_135_[97])
  );
  defparam _295_.LUT = 8'hca;
  defparam _295_.WIDTH = 32'd3;
  \$lut  _296_ (
    .A(a[98]),
    .Y(_084_)
  );
  defparam _296_.LUT = 2'h1;
  defparam _296_.WIDTH = 32'd1;
  \$lut  _297_ (
    .A({ b[98], _084_, a[98] }),
    .Y(_135_[98])
  );
  defparam _297_.LUT = 8'hca;
  defparam _297_.WIDTH = 32'd3;
  \$lut  _298_ (
    .A(a[99]),
    .Y(_085_)
  );
  defparam _298_.LUT = 2'h1;
  defparam _298_.WIDTH = 32'd1;
  \$lut  _299_ (
    .A({ b[99], _085_, a[99] }),
    .Y(_135_[99])
  );
  defparam _299_.LUT = 8'hca;
  defparam _299_.WIDTH = 32'd3;
  \$lut  _300_ (
    .A(a[100]),
    .Y(_086_)
  );
  defparam _300_.LUT = 2'h1;
  defparam _300_.WIDTH = 32'd1;
  \$lut  _301_ (
    .A({ b[100], _086_, a[100] }),
    .Y(_135_[100])
  );
  defparam _301_.LUT = 8'hca;
  defparam _301_.WIDTH = 32'd3;
  \$lut  _302_ (
    .A(a[101]),
    .Y(_087_)
  );
  defparam _302_.LUT = 2'h1;
  defparam _302_.WIDTH = 32'd1;
  \$lut  _303_ (
    .A({ b[101], _087_, a[101] }),
    .Y(_135_[101])
  );
  defparam _303_.LUT = 8'hca;
  defparam _303_.WIDTH = 32'd3;
  \$lut  _304_ (
    .A(a[102]),
    .Y(_088_)
  );
  defparam _304_.LUT = 2'h1;
  defparam _304_.WIDTH = 32'd1;
  \$lut  _305_ (
    .A({ b[102], _088_, a[102] }),
    .Y(_135_[102])
  );
  defparam _305_.LUT = 8'hca;
  defparam _305_.WIDTH = 32'd3;
  \$lut  _306_ (
    .A(a[103]),
    .Y(_089_)
  );
  defparam _306_.LUT = 2'h1;
  defparam _306_.WIDTH = 32'd1;
  \$lut  _307_ (
    .A({ b[103], _089_, a[103] }),
    .Y(_135_[103])
  );
  defparam _307_.LUT = 8'hca;
  defparam _307_.WIDTH = 32'd3;
  \$lut  _308_ (
    .A(a[104]),
    .Y(_090_)
  );
  defparam _308_.LUT = 2'h1;
  defparam _308_.WIDTH = 32'd1;
  \$lut  _309_ (
    .A({ b[104], _090_, a[104] }),
    .Y(_135_[104])
  );
  defparam _309_.LUT = 8'hca;
  defparam _309_.WIDTH = 32'd3;
  \$lut  _310_ (
    .A(a[105]),
    .Y(_091_)
  );
  defparam _310_.LUT = 2'h1;
  defparam _310_.WIDTH = 32'd1;
  \$lut  _311_ (
    .A({ b[105], _091_, a[105] }),
    .Y(_135_[105])
  );
  defparam _311_.LUT = 8'hca;
  defparam _311_.WIDTH = 32'd3;
  \$lut  _312_ (
    .A(a[106]),
    .Y(_092_)
  );
  defparam _312_.LUT = 2'h1;
  defparam _312_.WIDTH = 32'd1;
  \$lut  _313_ (
    .A({ b[106], _092_, a[106] }),
    .Y(_135_[106])
  );
  defparam _313_.LUT = 8'hca;
  defparam _313_.WIDTH = 32'd3;
  \$lut  _314_ (
    .A(a[107]),
    .Y(_093_)
  );
  defparam _314_.LUT = 2'h1;
  defparam _314_.WIDTH = 32'd1;
  \$lut  _315_ (
    .A({ b[107], _093_, a[107] }),
    .Y(_135_[107])
  );
  defparam _315_.LUT = 8'hca;
  defparam _315_.WIDTH = 32'd3;
  \$lut  _316_ (
    .A(a[108]),
    .Y(_094_)
  );
  defparam _316_.LUT = 2'h1;
  defparam _316_.WIDTH = 32'd1;
  \$lut  _317_ (
    .A({ b[108], _094_, a[108] }),
    .Y(_135_[108])
  );
  defparam _317_.LUT = 8'hca;
  defparam _317_.WIDTH = 32'd3;
  \$lut  _318_ (
    .A(a[109]),
    .Y(_095_)
  );
  defparam _318_.LUT = 2'h1;
  defparam _318_.WIDTH = 32'd1;
  \$lut  _319_ (
    .A({ b[109], _095_, a[109] }),
    .Y(_135_[109])
  );
  defparam _319_.LUT = 8'hca;
  defparam _319_.WIDTH = 32'd3;
  \$lut  _320_ (
    .A(a[110]),
    .Y(_096_)
  );
  defparam _320_.LUT = 2'h1;
  defparam _320_.WIDTH = 32'd1;
  \$lut  _321_ (
    .A({ b[110], _096_, a[110] }),
    .Y(_135_[110])
  );
  defparam _321_.LUT = 8'hca;
  defparam _321_.WIDTH = 32'd3;
  \$lut  _322_ (
    .A(a[111]),
    .Y(_097_)
  );
  defparam _322_.LUT = 2'h1;
  defparam _322_.WIDTH = 32'd1;
  \$lut  _323_ (
    .A({ b[111], _097_, a[111] }),
    .Y(_135_[111])
  );
  defparam _323_.LUT = 8'hca;
  defparam _323_.WIDTH = 32'd3;
  \$lut  _324_ (
    .A(a[112]),
    .Y(_098_)
  );
  defparam _324_.LUT = 2'h1;
  defparam _324_.WIDTH = 32'd1;
  \$lut  _325_ (
    .A({ b[112], _098_, a[112] }),
    .Y(_135_[112])
  );
  defparam _325_.LUT = 8'hca;
  defparam _325_.WIDTH = 32'd3;
  \$lut  _326_ (
    .A(a[113]),
    .Y(_099_)
  );
  defparam _326_.LUT = 2'h1;
  defparam _326_.WIDTH = 32'd1;
  \$lut  _327_ (
    .A({ b[113], _099_, a[113] }),
    .Y(_135_[113])
  );
  defparam _327_.LUT = 8'hca;
  defparam _327_.WIDTH = 32'd3;
  \$lut  _328_ (
    .A(a[114]),
    .Y(_100_)
  );
  defparam _328_.LUT = 2'h1;
  defparam _328_.WIDTH = 32'd1;
  \$lut  _329_ (
    .A({ b[114], _100_, a[114] }),
    .Y(_135_[114])
  );
  defparam _329_.LUT = 8'hca;
  defparam _329_.WIDTH = 32'd3;
  \$lut  _330_ (
    .A(a[115]),
    .Y(_101_)
  );
  defparam _330_.LUT = 2'h1;
  defparam _330_.WIDTH = 32'd1;
  \$lut  _331_ (
    .A({ b[115], _101_, a[115] }),
    .Y(_135_[115])
  );
  defparam _331_.LUT = 8'hca;
  defparam _331_.WIDTH = 32'd3;
  \$lut  _332_ (
    .A(a[116]),
    .Y(_102_)
  );
  defparam _332_.LUT = 2'h1;
  defparam _332_.WIDTH = 32'd1;
  \$lut  _333_ (
    .A({ b[116], _102_, a[116] }),
    .Y(_135_[116])
  );
  defparam _333_.LUT = 8'hca;
  defparam _333_.WIDTH = 32'd3;
  \$lut  _334_ (
    .A(a[117]),
    .Y(_103_)
  );
  defparam _334_.LUT = 2'h1;
  defparam _334_.WIDTH = 32'd1;
  \$lut  _335_ (
    .A({ b[117], _103_, a[117] }),
    .Y(_135_[117])
  );
  defparam _335_.LUT = 8'hca;
  defparam _335_.WIDTH = 32'd3;
  \$lut  _336_ (
    .A(a[118]),
    .Y(_104_)
  );
  defparam _336_.LUT = 2'h1;
  defparam _336_.WIDTH = 32'd1;
  \$lut  _337_ (
    .A({ b[118], _104_, a[118] }),
    .Y(_135_[118])
  );
  defparam _337_.LUT = 8'hca;
  defparam _337_.WIDTH = 32'd3;
  \$lut  _338_ (
    .A(a[119]),
    .Y(_105_)
  );
  defparam _338_.LUT = 2'h1;
  defparam _338_.WIDTH = 32'd1;
  \$lut  _339_ (
    .A({ b[119], _105_, a[119] }),
    .Y(_135_[119])
  );
  defparam _339_.LUT = 8'hca;
  defparam _339_.WIDTH = 32'd3;
  \$lut  _340_ (
    .A(a[120]),
    .Y(_106_)
  );
  defparam _340_.LUT = 2'h1;
  defparam _340_.WIDTH = 32'd1;
  \$lut  _341_ (
    .A({ b[120], _106_, a[120] }),
    .Y(_135_[120])
  );
  defparam _341_.LUT = 8'hca;
  defparam _341_.WIDTH = 32'd3;
  \$lut  _342_ (
    .A(a[121]),
    .Y(_107_)
  );
  defparam _342_.LUT = 2'h1;
  defparam _342_.WIDTH = 32'd1;
  \$lut  _343_ (
    .A({ b[121], _107_, a[121] }),
    .Y(_135_[121])
  );
  defparam _343_.LUT = 8'hca;
  defparam _343_.WIDTH = 32'd3;
  \$lut  _344_ (
    .A(a[122]),
    .Y(_108_)
  );
  defparam _344_.LUT = 2'h1;
  defparam _344_.WIDTH = 32'd1;
  \$lut  _345_ (
    .A({ b[122], _108_, a[122] }),
    .Y(_135_[122])
  );
  defparam _345_.LUT = 8'hca;
  defparam _345_.WIDTH = 32'd3;
  \$lut  _346_ (
    .A(a[123]),
    .Y(_109_)
  );
  defparam _346_.LUT = 2'h1;
  defparam _346_.WIDTH = 32'd1;
  \$lut  _347_ (
    .A({ b[123], _109_, a[123] }),
    .Y(_135_[123])
  );
  defparam _347_.LUT = 8'hca;
  defparam _347_.WIDTH = 32'd3;
  \$lut  _348_ (
    .A(a[124]),
    .Y(_110_)
  );
  defparam _348_.LUT = 2'h1;
  defparam _348_.WIDTH = 32'd1;
  \$lut  _349_ (
    .A({ b[124], _110_, a[124] }),
    .Y(_135_[124])
  );
  defparam _349_.LUT = 8'hca;
  defparam _349_.WIDTH = 32'd3;
  \$lut  _350_ (
    .A(a[125]),
    .Y(_111_)
  );
  defparam _350_.LUT = 2'h1;
  defparam _350_.WIDTH = 32'd1;
  \$lut  _351_ (
    .A({ b[125], _111_, a[125] }),
    .Y(_135_[125])
  );
  defparam _351_.LUT = 8'hca;
  defparam _351_.WIDTH = 32'd3;
  \$lut  _352_ (
    .A(a[126]),
    .Y(_112_)
  );
  defparam _352_.LUT = 2'h1;
  defparam _352_.WIDTH = 32'd1;
  \$lut  _353_ (
    .A({ b[126], _112_, a[126] }),
    .Y(_135_[126])
  );
  defparam _353_.LUT = 8'hca;
  defparam _353_.WIDTH = 32'd3;
  \$lut  _354_ (
    .A(a[127]),
    .Y(_113_)
  );
  defparam _354_.LUT = 2'h1;
  defparam _354_.WIDTH = 32'd1;
  \$lut  _355_ (
    .A({ b[127], _113_, 1'h1 }),
    .Y(_001_)
  );
  defparam _355_.LUT = 8'hca;
  defparam _355_.WIDTH = 32'd3;
  \$lut  _356_ (
    .A({ b[127], _113_, a[127] }),
    .Y(_002_)
  );
  defparam _356_.LUT = 8'hca;
  defparam _356_.WIDTH = 32'd3;
  \$lut  _357_ (
    .A(_000_),
    .Y(_114_)
  );
  defparam _357_.LUT = 2'h1;
  defparam _357_.WIDTH = 32'd1;
  \$lut  _358_ (
    .A({ _002_, _114_, 1'h1 }),
    .Y(_003_)
  );
  defparam _358_.LUT = 8'hca;
  defparam _358_.WIDTH = 32'd3;
  \$lut  _359_ (
    .A(_001_),
    .Y(_115_)
  );
  defparam _359_.LUT = 2'h1;
  defparam _359_.WIDTH = 32'd1;
  \$lut  _360_ (
    .A({ _003_, _115_, 1'h1 }),
    .Y(cout)
  );
  defparam _360_.LUT = 8'hca;
  defparam _360_.WIDTH = 32'd3;
  \$lut  _361_ (
    .A({ _002_, _114_, _000_ }),
    .Y(sum[127])
  );
  defparam _361_.LUT = 8'hca;
  defparam _361_.WIDTH = 32'd3;
  \$lut  _362_ (
    .A(a[0]),
    .Y(_116_)
  );
  defparam _362_.LUT = 2'h1;
  defparam _362_.WIDTH = 32'd1;
  \$lut  _363_ (
    .A({ b[0], _116_, a[0] }),
    .Y(_135_[0])
  );
  defparam _363_.LUT = 8'hca;
  defparam _363_.WIDTH = 32'd3;
  \$lut  _364_ (
    .A(a[1]),
    .Y(_117_)
  );
  defparam _364_.LUT = 2'h1;
  defparam _364_.WIDTH = 32'd1;
  \$lut  _365_ (
    .A({ b[1], _117_, a[1] }),
    .Y(_135_[1])
  );
  defparam _365_.LUT = 8'hca;
  defparam _365_.WIDTH = 32'd3;
  \$lut  _366_ (
    .A(a[2]),
    .Y(_118_)
  );
  defparam _366_.LUT = 2'h1;
  defparam _366_.WIDTH = 32'd1;
  \$lut  _367_ (
    .A({ b[2], _118_, a[2] }),
    .Y(_135_[2])
  );
  defparam _367_.LUT = 8'hca;
  defparam _367_.WIDTH = 32'd3;
  \$lut  _368_ (
    .A(a[3]),
    .Y(_119_)
  );
  defparam _368_.LUT = 2'h1;
  defparam _368_.WIDTH = 32'd1;
  \$lut  _369_ (
    .A({ b[3], _119_, a[3] }),
    .Y(_135_[3])
  );
  defparam _369_.LUT = 8'hca;
  defparam _369_.WIDTH = 32'd3;
  \$lut  _370_ (
    .A(a[4]),
    .Y(_120_)
  );
  defparam _370_.LUT = 2'h1;
  defparam _370_.WIDTH = 32'd1;
  \$lut  _371_ (
    .A({ b[4], _120_, a[4] }),
    .Y(_135_[4])
  );
  defparam _371_.LUT = 8'hca;
  defparam _371_.WIDTH = 32'd3;
  \$lut  _372_ (
    .A(a[5]),
    .Y(_121_)
  );
  defparam _372_.LUT = 2'h1;
  defparam _372_.WIDTH = 32'd1;
  \$lut  _373_ (
    .A({ b[5], _121_, a[5] }),
    .Y(_135_[5])
  );
  defparam _373_.LUT = 8'hca;
  defparam _373_.WIDTH = 32'd3;
  \$lut  _374_ (
    .A(a[6]),
    .Y(_122_)
  );
  defparam _374_.LUT = 2'h1;
  defparam _374_.WIDTH = 32'd1;
  \$lut  _375_ (
    .A({ b[6], _122_, a[6] }),
    .Y(_135_[6])
  );
  defparam _375_.LUT = 8'hca;
  defparam _375_.WIDTH = 32'd3;
  \$lut  _376_ (
    .A(a[7]),
    .Y(_123_)
  );
  defparam _376_.LUT = 2'h1;
  defparam _376_.WIDTH = 32'd1;
  \$lut  _377_ (
    .A({ b[7], _123_, a[7] }),
    .Y(_135_[7])
  );
  defparam _377_.LUT = 8'hca;
  defparam _377_.WIDTH = 32'd3;
  \$lut  _378_ (
    .A(a[8]),
    .Y(_124_)
  );
  defparam _378_.LUT = 2'h1;
  defparam _378_.WIDTH = 32'd1;
  \$lut  _379_ (
    .A({ b[8], _124_, a[8] }),
    .Y(_135_[8])
  );
  defparam _379_.LUT = 8'hca;
  defparam _379_.WIDTH = 32'd3;
  \$lut  _380_ (
    .A(a[9]),
    .Y(_125_)
  );
  defparam _380_.LUT = 2'h1;
  defparam _380_.WIDTH = 32'd1;
  \$lut  _381_ (
    .A({ b[9], _125_, a[9] }),
    .Y(_135_[9])
  );
  defparam _381_.LUT = 8'hca;
  defparam _381_.WIDTH = 32'd3;
  \$lut  _382_ (
    .A(a[10]),
    .Y(_126_)
  );
  defparam _382_.LUT = 2'h1;
  defparam _382_.WIDTH = 32'd1;
  \$lut  _383_ (
    .A({ b[10], _126_, a[10] }),
    .Y(_135_[10])
  );
  defparam _383_.LUT = 8'hca;
  defparam _383_.WIDTH = 32'd3;
  \$lut  _384_ (
    .A(a[11]),
    .Y(_127_)
  );
  defparam _384_.LUT = 2'h1;
  defparam _384_.WIDTH = 32'd1;
  \$lut  _385_ (
    .A({ b[11], _127_, a[11] }),
    .Y(_135_[11])
  );
  defparam _385_.LUT = 8'hca;
  defparam _385_.WIDTH = 32'd3;
  \$lut  _386_ (
    .A(a[12]),
    .Y(_128_)
  );
  defparam _386_.LUT = 2'h1;
  defparam _386_.WIDTH = 32'd1;
  \$lut  _387_ (
    .A({ b[12], _128_, a[12] }),
    .Y(_135_[12])
  );
  defparam _387_.LUT = 8'hca;
  defparam _387_.WIDTH = 32'd3;
  \$lut  _388_ (
    .A(a[13]),
    .Y(_129_)
  );
  defparam _388_.LUT = 2'h1;
  defparam _388_.WIDTH = 32'd1;
  \$lut  _389_ (
    .A({ b[13], _129_, a[13] }),
    .Y(_135_[13])
  );
  defparam _389_.LUT = 8'hca;
  defparam _389_.WIDTH = 32'd3;
  \$lut  _390_ (
    .A(a[14]),
    .Y(_130_)
  );
  defparam _390_.LUT = 2'h1;
  defparam _390_.WIDTH = 32'd1;
  \$lut  _391_ (
    .A({ b[14], _130_, a[14] }),
    .Y(_135_[14])
  );
  defparam _391_.LUT = 8'hca;
  defparam _391_.WIDTH = 32'd3;
  \$lut  _392_ (
    .A(a[15]),
    .Y(_131_)
  );
  defparam _392_.LUT = 2'h1;
  defparam _392_.WIDTH = 32'd1;
  \$lut  _393_ (
    .A({ b[15], _131_, a[15] }),
    .Y(_135_[15])
  );
  defparam _393_.LUT = 8'hca;
  defparam _393_.WIDTH = 32'd3;
  \$lut  _394_ (
    .A(a[16]),
    .Y(_132_)
  );
  defparam _394_.LUT = 2'h1;
  defparam _394_.WIDTH = 32'd1;
  \$lut  _395_ (
    .A({ b[16], _132_, a[16] }),
    .Y(_135_[16])
  );
  defparam _395_.LUT = 8'hca;
  defparam _395_.WIDTH = 32'd3;
  \$lut  _396_ (
    .A(a[17]),
    .Y(_133_)
  );
  defparam _396_.LUT = 2'h1;
  defparam _396_.WIDTH = 32'd1;
  \$lut  _397_ (
    .A({ b[17], _133_, a[17] }),
    .Y(_135_[17])
  );
  defparam _397_.LUT = 8'hca;
  defparam _397_.WIDTH = 32'd3;
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:79.19-85.8" *)
  adder_carry _398_ (
    .cin(_134_[127]),
    .g(1'h0),
    .p(1'h0),
    .sumout(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _399_ (
    .cin(_134_[0]),
    .cout(_134_[1]),
    .g(a[0]),
    .p(_135_[0]),
    .sumout(sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _400_ (
    .cin(_134_[100]),
    .cout(_134_[101]),
    .g(a[100]),
    .p(_135_[100]),
    .sumout(sum[100])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _401_ (
    .cin(_134_[101]),
    .cout(_134_[102]),
    .g(a[101]),
    .p(_135_[101]),
    .sumout(sum[101])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _402_ (
    .cin(_134_[102]),
    .cout(_134_[103]),
    .g(a[102]),
    .p(_135_[102]),
    .sumout(sum[102])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _403_ (
    .cin(_134_[103]),
    .cout(_134_[104]),
    .g(a[103]),
    .p(_135_[103]),
    .sumout(sum[103])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _404_ (
    .cin(_134_[104]),
    .cout(_134_[105]),
    .g(a[104]),
    .p(_135_[104]),
    .sumout(sum[104])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _405_ (
    .cin(_134_[105]),
    .cout(_134_[106]),
    .g(a[105]),
    .p(_135_[105]),
    .sumout(sum[105])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _406_ (
    .cin(_134_[106]),
    .cout(_134_[107]),
    .g(a[106]),
    .p(_135_[106]),
    .sumout(sum[106])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _407_ (
    .cin(_134_[107]),
    .cout(_134_[108]),
    .g(a[107]),
    .p(_135_[107]),
    .sumout(sum[107])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _408_ (
    .cin(_134_[108]),
    .cout(_134_[109]),
    .g(a[108]),
    .p(_135_[108]),
    .sumout(sum[108])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _409_ (
    .cin(_134_[109]),
    .cout(_134_[110]),
    .g(a[109]),
    .p(_135_[109]),
    .sumout(sum[109])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _410_ (
    .cin(_134_[10]),
    .cout(_134_[11]),
    .g(a[10]),
    .p(_135_[10]),
    .sumout(sum[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _411_ (
    .cin(_134_[110]),
    .cout(_134_[111]),
    .g(a[110]),
    .p(_135_[110]),
    .sumout(sum[110])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _412_ (
    .cin(_134_[111]),
    .cout(_134_[112]),
    .g(a[111]),
    .p(_135_[111]),
    .sumout(sum[111])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _413_ (
    .cin(_134_[112]),
    .cout(_134_[113]),
    .g(a[112]),
    .p(_135_[112]),
    .sumout(sum[112])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _414_ (
    .cin(_134_[113]),
    .cout(_134_[114]),
    .g(a[113]),
    .p(_135_[113]),
    .sumout(sum[113])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _415_ (
    .cin(_134_[114]),
    .cout(_134_[115]),
    .g(a[114]),
    .p(_135_[114]),
    .sumout(sum[114])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _416_ (
    .cin(_134_[115]),
    .cout(_134_[116]),
    .g(a[115]),
    .p(_135_[115]),
    .sumout(sum[115])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _417_ (
    .cin(_134_[116]),
    .cout(_134_[117]),
    .g(a[116]),
    .p(_135_[116]),
    .sumout(sum[116])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _418_ (
    .cin(_134_[117]),
    .cout(_134_[118]),
    .g(a[117]),
    .p(_135_[117]),
    .sumout(sum[117])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _419_ (
    .cin(_134_[118]),
    .cout(_134_[119]),
    .g(a[118]),
    .p(_135_[118]),
    .sumout(sum[118])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _420_ (
    .cin(_134_[119]),
    .cout(_134_[120]),
    .g(a[119]),
    .p(_135_[119]),
    .sumout(sum[119])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _421_ (
    .cin(_134_[11]),
    .cout(_134_[12]),
    .g(a[11]),
    .p(_135_[11]),
    .sumout(sum[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _422_ (
    .cin(_134_[120]),
    .cout(_134_[121]),
    .g(a[120]),
    .p(_135_[120]),
    .sumout(sum[120])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _423_ (
    .cin(_134_[121]),
    .cout(_134_[122]),
    .g(a[121]),
    .p(_135_[121]),
    .sumout(sum[121])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _424_ (
    .cin(_134_[122]),
    .cout(_134_[123]),
    .g(a[122]),
    .p(_135_[122]),
    .sumout(sum[122])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _425_ (
    .cin(_134_[123]),
    .cout(_134_[124]),
    .g(a[123]),
    .p(_135_[123]),
    .sumout(sum[123])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _426_ (
    .cin(_134_[124]),
    .cout(_134_[125]),
    .g(a[124]),
    .p(_135_[124]),
    .sumout(sum[124])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _427_ (
    .cin(_134_[125]),
    .cout(_134_[126]),
    .g(a[125]),
    .p(_135_[125]),
    .sumout(sum[125])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _428_ (
    .cin(_134_[126]),
    .cout(_134_[127]),
    .g(a[126]),
    .p(_135_[126]),
    .sumout(sum[126])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _429_ (
    .cin(_134_[12]),
    .cout(_134_[13]),
    .g(a[12]),
    .p(_135_[12]),
    .sumout(sum[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _430_ (
    .cin(_134_[13]),
    .cout(_134_[14]),
    .g(a[13]),
    .p(_135_[13]),
    .sumout(sum[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _431_ (
    .cin(_134_[14]),
    .cout(_134_[15]),
    .g(a[14]),
    .p(_135_[14]),
    .sumout(sum[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _432_ (
    .cin(_134_[15]),
    .cout(_134_[16]),
    .g(a[15]),
    .p(_135_[15]),
    .sumout(sum[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _433_ (
    .cin(_134_[16]),
    .cout(_134_[17]),
    .g(a[16]),
    .p(_135_[16]),
    .sumout(sum[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _434_ (
    .cin(_134_[17]),
    .cout(_134_[18]),
    .g(a[17]),
    .p(_135_[17]),
    .sumout(sum[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _435_ (
    .cin(_134_[18]),
    .cout(_134_[19]),
    .g(a[18]),
    .p(_135_[18]),
    .sumout(sum[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _436_ (
    .cin(_134_[19]),
    .cout(_134_[20]),
    .g(a[19]),
    .p(_135_[19]),
    .sumout(sum[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _437_ (
    .cin(_134_[1]),
    .cout(_134_[2]),
    .g(a[1]),
    .p(_135_[1]),
    .sumout(sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _438_ (
    .cin(_134_[20]),
    .cout(_134_[21]),
    .g(a[20]),
    .p(_135_[20]),
    .sumout(sum[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _439_ (
    .cin(_134_[21]),
    .cout(_134_[22]),
    .g(a[21]),
    .p(_135_[21]),
    .sumout(sum[21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _440_ (
    .cin(_134_[22]),
    .cout(_134_[23]),
    .g(a[22]),
    .p(_135_[22]),
    .sumout(sum[22])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _441_ (
    .cin(_134_[23]),
    .cout(_134_[24]),
    .g(a[23]),
    .p(_135_[23]),
    .sumout(sum[23])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _442_ (
    .cin(_134_[24]),
    .cout(_134_[25]),
    .g(a[24]),
    .p(_135_[24]),
    .sumout(sum[24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _443_ (
    .cin(_134_[25]),
    .cout(_134_[26]),
    .g(a[25]),
    .p(_135_[25]),
    .sumout(sum[25])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _444_ (
    .cin(_134_[26]),
    .cout(_134_[27]),
    .g(a[26]),
    .p(_135_[26]),
    .sumout(sum[26])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _445_ (
    .cin(_134_[27]),
    .cout(_134_[28]),
    .g(a[27]),
    .p(_135_[27]),
    .sumout(sum[27])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _446_ (
    .cin(_134_[28]),
    .cout(_134_[29]),
    .g(a[28]),
    .p(_135_[28]),
    .sumout(sum[28])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _447_ (
    .cin(_134_[29]),
    .cout(_134_[30]),
    .g(a[29]),
    .p(_135_[29]),
    .sumout(sum[29])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _448_ (
    .cin(_134_[2]),
    .cout(_134_[3]),
    .g(a[2]),
    .p(_135_[2]),
    .sumout(sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _449_ (
    .cin(_134_[30]),
    .cout(_134_[31]),
    .g(a[30]),
    .p(_135_[30]),
    .sumout(sum[30])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _450_ (
    .cin(_134_[31]),
    .cout(_134_[32]),
    .g(a[31]),
    .p(_135_[31]),
    .sumout(sum[31])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _451_ (
    .cin(_134_[32]),
    .cout(_134_[33]),
    .g(a[32]),
    .p(_135_[32]),
    .sumout(sum[32])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _452_ (
    .cin(_134_[33]),
    .cout(_134_[34]),
    .g(a[33]),
    .p(_135_[33]),
    .sumout(sum[33])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _453_ (
    .cin(_134_[34]),
    .cout(_134_[35]),
    .g(a[34]),
    .p(_135_[34]),
    .sumout(sum[34])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _454_ (
    .cin(_134_[35]),
    .cout(_134_[36]),
    .g(a[35]),
    .p(_135_[35]),
    .sumout(sum[35])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _455_ (
    .cin(_134_[36]),
    .cout(_134_[37]),
    .g(a[36]),
    .p(_135_[36]),
    .sumout(sum[36])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _456_ (
    .cin(_134_[37]),
    .cout(_134_[38]),
    .g(a[37]),
    .p(_135_[37]),
    .sumout(sum[37])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _457_ (
    .cin(_134_[38]),
    .cout(_134_[39]),
    .g(a[38]),
    .p(_135_[38]),
    .sumout(sum[38])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _458_ (
    .cin(_134_[39]),
    .cout(_134_[40]),
    .g(a[39]),
    .p(_135_[39]),
    .sumout(sum[39])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _459_ (
    .cin(_134_[3]),
    .cout(_134_[4]),
    .g(a[3]),
    .p(_135_[3]),
    .sumout(sum[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _460_ (
    .cin(_134_[40]),
    .cout(_134_[41]),
    .g(a[40]),
    .p(_135_[40]),
    .sumout(sum[40])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _461_ (
    .cin(_134_[41]),
    .cout(_134_[42]),
    .g(a[41]),
    .p(_135_[41]),
    .sumout(sum[41])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _462_ (
    .cin(_134_[42]),
    .cout(_134_[43]),
    .g(a[42]),
    .p(_135_[42]),
    .sumout(sum[42])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _463_ (
    .cin(_134_[43]),
    .cout(_134_[44]),
    .g(a[43]),
    .p(_135_[43]),
    .sumout(sum[43])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _464_ (
    .cin(_134_[44]),
    .cout(_134_[45]),
    .g(a[44]),
    .p(_135_[44]),
    .sumout(sum[44])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _465_ (
    .cin(_134_[45]),
    .cout(_134_[46]),
    .g(a[45]),
    .p(_135_[45]),
    .sumout(sum[45])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _466_ (
    .cin(_134_[46]),
    .cout(_134_[47]),
    .g(a[46]),
    .p(_135_[46]),
    .sumout(sum[46])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _467_ (
    .cin(_134_[47]),
    .cout(_134_[48]),
    .g(a[47]),
    .p(_135_[47]),
    .sumout(sum[47])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _468_ (
    .cin(_134_[48]),
    .cout(_134_[49]),
    .g(a[48]),
    .p(_135_[48]),
    .sumout(sum[48])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _469_ (
    .cin(_134_[49]),
    .cout(_134_[50]),
    .g(a[49]),
    .p(_135_[49]),
    .sumout(sum[49])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _470_ (
    .cin(_134_[4]),
    .cout(_134_[5]),
    .g(a[4]),
    .p(_135_[4]),
    .sumout(sum[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _471_ (
    .cin(_134_[50]),
    .cout(_134_[51]),
    .g(a[50]),
    .p(_135_[50]),
    .sumout(sum[50])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _472_ (
    .cin(_134_[51]),
    .cout(_134_[52]),
    .g(a[51]),
    .p(_135_[51]),
    .sumout(sum[51])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _473_ (
    .cin(_134_[52]),
    .cout(_134_[53]),
    .g(a[52]),
    .p(_135_[52]),
    .sumout(sum[52])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _474_ (
    .cin(_134_[53]),
    .cout(_134_[54]),
    .g(a[53]),
    .p(_135_[53]),
    .sumout(sum[53])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _475_ (
    .cin(_134_[54]),
    .cout(_134_[55]),
    .g(a[54]),
    .p(_135_[54]),
    .sumout(sum[54])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _476_ (
    .cin(_134_[55]),
    .cout(_134_[56]),
    .g(a[55]),
    .p(_135_[55]),
    .sumout(sum[55])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _477_ (
    .cin(_134_[56]),
    .cout(_134_[57]),
    .g(a[56]),
    .p(_135_[56]),
    .sumout(sum[56])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _478_ (
    .cin(_134_[57]),
    .cout(_134_[58]),
    .g(a[57]),
    .p(_135_[57]),
    .sumout(sum[57])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _479_ (
    .cin(_134_[58]),
    .cout(_134_[59]),
    .g(a[58]),
    .p(_135_[58]),
    .sumout(sum[58])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _480_ (
    .cin(_134_[59]),
    .cout(_134_[60]),
    .g(a[59]),
    .p(_135_[59]),
    .sumout(sum[59])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _481_ (
    .cin(_134_[5]),
    .cout(_134_[6]),
    .g(a[5]),
    .p(_135_[5]),
    .sumout(sum[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _482_ (
    .cin(_134_[60]),
    .cout(_134_[61]),
    .g(a[60]),
    .p(_135_[60]),
    .sumout(sum[60])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _483_ (
    .cin(_134_[61]),
    .cout(_134_[62]),
    .g(a[61]),
    .p(_135_[61]),
    .sumout(sum[61])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _484_ (
    .cin(_134_[62]),
    .cout(_134_[63]),
    .g(a[62]),
    .p(_135_[62]),
    .sumout(sum[62])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _485_ (
    .cin(_134_[63]),
    .cout(_134_[64]),
    .g(a[63]),
    .p(_135_[63]),
    .sumout(sum[63])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _486_ (
    .cin(_134_[64]),
    .cout(_134_[65]),
    .g(a[64]),
    .p(_135_[64]),
    .sumout(sum[64])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _487_ (
    .cin(_134_[65]),
    .cout(_134_[66]),
    .g(a[65]),
    .p(_135_[65]),
    .sumout(sum[65])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _488_ (
    .cin(_134_[66]),
    .cout(_134_[67]),
    .g(a[66]),
    .p(_135_[66]),
    .sumout(sum[66])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _489_ (
    .cin(_134_[67]),
    .cout(_134_[68]),
    .g(a[67]),
    .p(_135_[67]),
    .sumout(sum[67])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _490_ (
    .cin(_134_[68]),
    .cout(_134_[69]),
    .g(a[68]),
    .p(_135_[68]),
    .sumout(sum[68])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _491_ (
    .cin(_134_[69]),
    .cout(_134_[70]),
    .g(a[69]),
    .p(_135_[69]),
    .sumout(sum[69])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _492_ (
    .cin(_134_[6]),
    .cout(_134_[7]),
    .g(a[6]),
    .p(_135_[6]),
    .sumout(sum[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _493_ (
    .cin(_134_[70]),
    .cout(_134_[71]),
    .g(a[70]),
    .p(_135_[70]),
    .sumout(sum[70])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _494_ (
    .cin(_134_[71]),
    .cout(_134_[72]),
    .g(a[71]),
    .p(_135_[71]),
    .sumout(sum[71])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _495_ (
    .cin(_134_[72]),
    .cout(_134_[73]),
    .g(a[72]),
    .p(_135_[72]),
    .sumout(sum[72])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _496_ (
    .cin(_134_[73]),
    .cout(_134_[74]),
    .g(a[73]),
    .p(_135_[73]),
    .sumout(sum[73])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _497_ (
    .cin(_134_[74]),
    .cout(_134_[75]),
    .g(a[74]),
    .p(_135_[74]),
    .sumout(sum[74])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _498_ (
    .cin(_134_[75]),
    .cout(_134_[76]),
    .g(a[75]),
    .p(_135_[75]),
    .sumout(sum[75])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _499_ (
    .cin(_134_[76]),
    .cout(_134_[77]),
    .g(a[76]),
    .p(_135_[76]),
    .sumout(sum[76])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _500_ (
    .cin(_134_[77]),
    .cout(_134_[78]),
    .g(a[77]),
    .p(_135_[77]),
    .sumout(sum[77])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _501_ (
    .cin(_134_[78]),
    .cout(_134_[79]),
    .g(a[78]),
    .p(_135_[78]),
    .sumout(sum[78])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _502_ (
    .cin(_134_[79]),
    .cout(_134_[80]),
    .g(a[79]),
    .p(_135_[79]),
    .sumout(sum[79])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _503_ (
    .cin(_134_[7]),
    .cout(_134_[8]),
    .g(a[7]),
    .p(_135_[7]),
    .sumout(sum[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _504_ (
    .cin(_134_[80]),
    .cout(_134_[81]),
    .g(a[80]),
    .p(_135_[80]),
    .sumout(sum[80])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _505_ (
    .cin(_134_[81]),
    .cout(_134_[82]),
    .g(a[81]),
    .p(_135_[81]),
    .sumout(sum[81])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _506_ (
    .cin(_134_[82]),
    .cout(_134_[83]),
    .g(a[82]),
    .p(_135_[82]),
    .sumout(sum[82])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _507_ (
    .cin(_134_[83]),
    .cout(_134_[84]),
    .g(a[83]),
    .p(_135_[83]),
    .sumout(sum[83])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _508_ (
    .cin(_134_[84]),
    .cout(_134_[85]),
    .g(a[84]),
    .p(_135_[84]),
    .sumout(sum[84])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _509_ (
    .cin(_134_[85]),
    .cout(_134_[86]),
    .g(a[85]),
    .p(_135_[85]),
    .sumout(sum[85])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _510_ (
    .cin(_134_[86]),
    .cout(_134_[87]),
    .g(a[86]),
    .p(_135_[86]),
    .sumout(sum[86])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _511_ (
    .cin(_134_[87]),
    .cout(_134_[88]),
    .g(a[87]),
    .p(_135_[87]),
    .sumout(sum[87])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _512_ (
    .cin(_134_[88]),
    .cout(_134_[89]),
    .g(a[88]),
    .p(_135_[88]),
    .sumout(sum[88])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _513_ (
    .cin(_134_[89]),
    .cout(_134_[90]),
    .g(a[89]),
    .p(_135_[89]),
    .sumout(sum[89])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _514_ (
    .cin(_134_[8]),
    .cout(_134_[9]),
    .g(a[8]),
    .p(_135_[8]),
    .sumout(sum[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _515_ (
    .cin(_134_[90]),
    .cout(_134_[91]),
    .g(a[90]),
    .p(_135_[90]),
    .sumout(sum[90])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _516_ (
    .cin(_134_[91]),
    .cout(_134_[92]),
    .g(a[91]),
    .p(_135_[91]),
    .sumout(sum[91])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _517_ (
    .cin(_134_[92]),
    .cout(_134_[93]),
    .g(a[92]),
    .p(_135_[92]),
    .sumout(sum[92])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _518_ (
    .cin(_134_[93]),
    .cout(_134_[94]),
    .g(a[93]),
    .p(_135_[93]),
    .sumout(sum[93])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _519_ (
    .cin(_134_[94]),
    .cout(_134_[95]),
    .g(a[94]),
    .p(_135_[94]),
    .sumout(sum[94])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _520_ (
    .cin(_134_[95]),
    .cout(_134_[96]),
    .g(a[95]),
    .p(_135_[95]),
    .sumout(sum[95])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _521_ (
    .cin(_134_[96]),
    .cout(_134_[97]),
    .g(a[96]),
    .p(_135_[96]),
    .sumout(sum[96])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _522_ (
    .cin(_134_[97]),
    .cout(_134_[98]),
    .g(a[97]),
    .p(_135_[97]),
    .sumout(sum[97])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _523_ (
    .cin(_134_[98]),
    .cout(_134_[99]),
    .g(a[98]),
    .p(_135_[98]),
    .sumout(sum[98])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _524_ (
    .cin(_134_[99]),
    .cout(_134_[100]),
    .g(a[99]),
    .p(_135_[99]),
    .sumout(sum[99])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry _525_ (
    .cin(_134_[9]),
    .cout(_134_[10]),
    .g(a[9]),
    .p(_135_[9]),
    .sumout(sum[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./rtl/adder_128/adder_128.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:54.19-60.8" *)
  adder_carry _526_ (
    .cout(_134_[0]),
    .g(cin),
    .p(1'h0)
  );
  assign _134_[129:128] = { 1'h0, cout };
  assign _135_[128] = 1'h0;
endmodule
