#!/bin/bash
#
# COPYRIGHT NOTICE
# Copyright 2021-2023 Rapid Silicon, Inc. All Rights Reserved.
#
base_path=`dirname $BASH_SOURCE`
ENC_PATH=`( cd "$base_path" && pwd )`
sysname=$(uname -s)
case $sysname in
    Linux)
        mach=$(uname -m)
        case $mach in
            x86_64)
                glibcVersion=$(ldd --version | awk '/ldd/{print $NF}' \
                                             | sed -n 's/2\.\([0-9]*\)/\1/p')
                if [ "$glibcVersion" -gt 12 ]; then
                    plat="linux64"
                else
                    plat="linux-legacy"
                fi
                ;;
            i[3-6]86*)
                echo "Linux 32 bit is no longer supported."
                exit 1
                ;;
            *)
                echo "machine $mach not supported on linux"
                exit 1
                ;;
        esac
        ;;
    *)
        echo "Operating system $sysname not supported."
        exit 1
        ;;
esac
export LD_LIBRARY_PATH=$ENC_PATH/../lib
$ENC_PATH/../lib/enc_verilog "$@"

