#!/bin/bash
#
# COPYRIGHT NOTICE
# Copyright 2021-2023 Rapid Silicon, Inc. All Rights Reserved.
#
base_path=`dirname $BASH_SOURCE`
ENC_PATH=`( cd "$base_path" && pwd )`
sysname=$(uname -s)
case $sysname in
    Linux)
        mach=$(uname -m)
        case $mach in
            x86_64)
                glibcVersion=$(ldd --version | awk '/ldd/{print $NF}' \
                                             | sed -n 's/2\.\([0-9]*\)/\1/p')
                if [ "$glibcVersion" -gt 12 ]; then
                    plat="linux64"
                else
                    plat="linux-legacy"
                fi
                ;;
            i[3-6]86*)
                echo "Linux 32 bit is no longer supported."
                exit 1
                ;;
            *)
                echo "machine $mach not supported on linux"
                exit 1
                ;;
        esac
        ;;
    *)
        echo "Operating system $sysname not supported."
        exit 1
        ;;
esac
export LD_LIBRARY_PATH=$ENC_PATH/../lib
usage()
{
  echo -e "Usage:\trs_encrypt\n\t\t\t\t[ -h | --help]\t\t\tshow the help
                         \t[ -k | --keyfile ]\t\tFile containing the key if not embeded in HDL file
			        [ -f | --hdl-files]\t\tSpace separated HDL files with extension .v or .sv"
  exit 2
}

if [ $# -eq 0 ]; then
    echo "No arguments provided"
    usage
    exit 1
fi

PARSED_ARGUMENTS=$(getopt -a -n $0 -o hk:f: --long help,keyfile:,hdl-files: -- "$@")
VALID_ARGUMENTS=$?
if [ "$VALID_ARGUMENTS" != "0" ]; then
  usage
fi
eval set -- "$PARSED_ARGUMENTS"
while :
do
  case "$1" in   
    -h | --help)        usage  ;;
    -k | --keyfile)     kf="$2";   shift 2 ;;
    -f | --hdl-files)        hdlf="$2"; shift 2 ;;
    --) shift; break ;;
    *) break ;;
  esac
done
[ -z $hdlf ] && usage
$ENC_PATH/enc_verilog $kf $hdlf $@
