/* Generated by Yosys 0.17+76 (git sha1 035496b50, gcc 9.1.0 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "./rtl/adder_64/adder_64.v:3.1-12.10" *)
module adder_64(cout, sum, a, b, cin);
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:43.7-43.9" *)
  wire \$abc$1209$abc$385$auto$alumacc.cc:485:replace_alu$3.co ;
  wire \$abc$1209$abc$661$abc$592$new_n195__new__new_ ;
  wire \$abc$1209$abc$661$abc$592$new_n196__new__new_ ;
  wire \$abc$1209$abc$661$abc$592$new_n197__new__new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1004[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1009[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1014[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1019[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1024[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1029[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1034[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1039[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1044[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1049[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1054[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1059[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1064[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1069[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1074[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1079[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1084[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1089[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1094[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1099[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1104[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1109[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1114[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1119[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1124[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1129[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1134[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1139[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1144[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1149[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1154[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1159[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1164[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1169[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1174[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1179[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1184[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1189[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1194[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1199[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1204[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$869[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$879[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$884[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$894[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$899[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$904[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$909[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$914[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$919[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$924[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$929[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$934[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$939[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$944[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$949[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$954[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$959[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$964[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$969[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$974[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$979[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$984[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$989[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$994[1]_new_ ;
  wire \$abc$1209$auto$simplemap.cc:333:simplemap_lut$999[1]_new_ ;
  (* force_downto = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:47.19-47.20" *)
  wire [65:0] \$auto$alumacc.cc:485:replace_alu$3.C ;
  (* force_downto = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:49.21-49.22" *)
  (* unused_bits = "63" *)
  wire [64:0] \$auto$alumacc.cc:485:replace_alu$3.S ;
  (* src = "./rtl/adder_64/adder_64.v:8.18-8.19" *)
  input [63:0] a;
  wire [63:0] a;
  (* src = "./rtl/adder_64/adder_64.v:8.21-8.22" *)
  input [63:0] b;
  wire [63:0] b;
  (* src = "./rtl/adder_64/adder_64.v:7.7-7.10" *)
  input cin;
  wire cin;
  (* src = "./rtl/adder_64/adder_64.v:5.8-5.12" *)
  output cout;
  wire cout;
  (* src = "./rtl/adder_64/adder_64.v:6.19-6.22" *)
  output [63:0] sum;
  wire [63:0] sum;
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$999[1]_new_  = 2'h1 >> a[21];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [21] = 8'hca >> { b[21], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$999[1]_new_ , a[21] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1004[1]_new_  = 2'h1 >> a[22];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [22] = 8'hca >> { b[22], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1004[1]_new_ , a[22] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1009[1]_new_  = 2'h1 >> a[23];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [23] = 8'hca >> { b[23], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1009[1]_new_ , a[23] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1014[1]_new_  = 2'h1 >> a[24];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [24] = 8'hca >> { b[24], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1014[1]_new_ , a[24] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1019[1]_new_  = 2'h1 >> a[25];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [25] = 8'hca >> { b[25], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1019[1]_new_ , a[25] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1024[1]_new_  = 2'h1 >> a[26];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [26] = 8'hca >> { b[26], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1024[1]_new_ , a[26] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1029[1]_new_  = 2'h1 >> a[27];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [27] = 8'hca >> { b[27], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1029[1]_new_ , a[27] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1034[1]_new_  = 2'h1 >> a[28];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [28] = 8'hca >> { b[28], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1034[1]_new_ , a[28] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1039[1]_new_  = 2'h1 >> a[29];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [29] = 8'hca >> { b[29], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1039[1]_new_ , a[29] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1044[1]_new_  = 2'h1 >> a[30];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [30] = 8'hca >> { b[30], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1044[1]_new_ , a[30] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1049[1]_new_  = 2'h1 >> a[31];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [31] = 8'hca >> { b[31], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1049[1]_new_ , a[31] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1054[1]_new_  = 2'h1 >> a[32];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [32] = 8'hca >> { b[32], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1054[1]_new_ , a[32] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1059[1]_new_  = 2'h1 >> a[33];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [33] = 8'hca >> { b[33], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1059[1]_new_ , a[33] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1064[1]_new_  = 2'h1 >> a[34];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [34] = 8'hca >> { b[34], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1064[1]_new_ , a[34] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1069[1]_new_  = 2'h1 >> a[35];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [35] = 8'hca >> { b[35], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1069[1]_new_ , a[35] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1074[1]_new_  = 2'h1 >> a[36];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [36] = 8'hca >> { b[36], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1074[1]_new_ , a[36] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1079[1]_new_  = 2'h1 >> a[37];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [37] = 8'hca >> { b[37], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1079[1]_new_ , a[37] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1084[1]_new_  = 2'h1 >> a[38];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [38] = 8'hca >> { b[38], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1084[1]_new_ , a[38] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1089[1]_new_  = 2'h1 >> a[39];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [39] = 8'hca >> { b[39], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1089[1]_new_ , a[39] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1094[1]_new_  = 2'h1 >> a[40];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [40] = 8'hca >> { b[40], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1094[1]_new_ , a[40] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1099[1]_new_  = 2'h1 >> a[41];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [41] = 8'hca >> { b[41], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1099[1]_new_ , a[41] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1104[1]_new_  = 2'h1 >> a[42];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [42] = 8'hca >> { b[42], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1104[1]_new_ , a[42] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1109[1]_new_  = 2'h1 >> a[43];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [43] = 8'hca >> { b[43], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1109[1]_new_ , a[43] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1114[1]_new_  = 2'h1 >> a[44];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [44] = 8'hca >> { b[44], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1114[1]_new_ , a[44] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1119[1]_new_  = 2'h1 >> a[45];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [45] = 8'hca >> { b[45], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1119[1]_new_ , a[45] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1124[1]_new_  = 2'h1 >> a[46];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [46] = 8'hca >> { b[46], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1124[1]_new_ , a[46] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1129[1]_new_  = 2'h1 >> a[47];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [47] = 8'hca >> { b[47], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1129[1]_new_ , a[47] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1134[1]_new_  = 2'h1 >> a[48];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [48] = 8'hca >> { b[48], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1134[1]_new_ , a[48] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1139[1]_new_  = 2'h1 >> a[49];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [49] = 8'hca >> { b[49], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1139[1]_new_ , a[49] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1144[1]_new_  = 2'h1 >> a[50];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [50] = 8'hca >> { b[50], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1144[1]_new_ , a[50] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1149[1]_new_  = 2'h1 >> a[51];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [51] = 8'hca >> { b[51], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1149[1]_new_ , a[51] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1154[1]_new_  = 2'h1 >> a[52];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [52] = 8'hca >> { b[52], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1154[1]_new_ , a[52] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1159[1]_new_  = 2'h1 >> a[53];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [53] = 8'hca >> { b[53], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1159[1]_new_ , a[53] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1164[1]_new_  = 2'h1 >> a[54];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [54] = 8'hca >> { b[54], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1164[1]_new_ , a[54] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1169[1]_new_  = 2'h1 >> a[55];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [55] = 8'hca >> { b[55], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1169[1]_new_ , a[55] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1174[1]_new_  = 2'h1 >> a[56];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [56] = 8'hca >> { b[56], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1174[1]_new_ , a[56] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1179[1]_new_  = 2'h1 >> a[57];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [57] = 8'hca >> { b[57], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1179[1]_new_ , a[57] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1184[1]_new_  = 2'h1 >> a[58];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [58] = 8'hca >> { b[58], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1184[1]_new_ , a[58] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1189[1]_new_  = 2'h1 >> a[59];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [59] = 8'hca >> { b[59], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1189[1]_new_ , a[59] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1194[1]_new_  = 2'h1 >> a[60];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [60] = 8'hca >> { b[60], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1194[1]_new_ , a[60] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1199[1]_new_  = 2'h1 >> a[61];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [61] = 8'hca >> { b[61], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1199[1]_new_ , a[61] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1204[1]_new_  = 2'h1 >> a[62];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [62] = 8'hca >> { b[62], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$1204[1]_new_ , a[62] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$869[1]_new_  = 2'h1 >> a[63];
  assign \$abc$1209$abc$661$abc$592$new_n195__new__new_  = 8'hca >> { b[63], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$869[1]_new_ , 1'h1 };
  assign \$abc$1209$abc$661$abc$592$new_n196__new__new_  = 8'hca >> { b[63], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$869[1]_new_ , a[63] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$879[1]_new_  = 2'h1 >> \$abc$1209$abc$385$auto$alumacc.cc:485:replace_alu$3.co ;
  assign \$abc$1209$abc$661$abc$592$new_n197__new__new_  = 8'hca >> { \$abc$1209$abc$661$abc$592$new_n196__new__new_ , \$abc$1209$auto$simplemap.cc:333:simplemap_lut$879[1]_new_ , 1'h1 };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$884[1]_new_  = 2'h1 >> \$abc$1209$abc$661$abc$592$new_n195__new__new_ ;
  assign cout = 8'hca >> { \$abc$1209$abc$661$abc$592$new_n197__new__new_ , \$abc$1209$auto$simplemap.cc:333:simplemap_lut$884[1]_new_ , 1'h1 };
  assign sum[63] = 8'hca >> { \$abc$1209$abc$661$abc$592$new_n196__new__new_ , \$abc$1209$auto$simplemap.cc:333:simplemap_lut$879[1]_new_ , \$abc$1209$abc$385$auto$alumacc.cc:485:replace_alu$3.co  };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$894[1]_new_  = 2'h1 >> a[0];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [0] = 8'hca >> { b[0], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$894[1]_new_ , a[0] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$899[1]_new_  = 2'h1 >> a[1];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [1] = 8'hca >> { b[1], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$899[1]_new_ , a[1] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$904[1]_new_  = 2'h1 >> a[2];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [2] = 8'hca >> { b[2], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$904[1]_new_ , a[2] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$909[1]_new_  = 2'h1 >> a[3];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [3] = 8'hca >> { b[3], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$909[1]_new_ , a[3] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$914[1]_new_  = 2'h1 >> a[4];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [4] = 8'hca >> { b[4], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$914[1]_new_ , a[4] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$919[1]_new_  = 2'h1 >> a[5];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [5] = 8'hca >> { b[5], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$919[1]_new_ , a[5] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$924[1]_new_  = 2'h1 >> a[6];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [6] = 8'hca >> { b[6], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$924[1]_new_ , a[6] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$929[1]_new_  = 2'h1 >> a[7];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [7] = 8'hca >> { b[7], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$929[1]_new_ , a[7] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$934[1]_new_  = 2'h1 >> a[8];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [8] = 8'hca >> { b[8], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$934[1]_new_ , a[8] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$939[1]_new_  = 2'h1 >> a[9];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [9] = 8'hca >> { b[9], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$939[1]_new_ , a[9] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$944[1]_new_  = 2'h1 >> a[10];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [10] = 8'hca >> { b[10], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$944[1]_new_ , a[10] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$949[1]_new_  = 2'h1 >> a[11];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [11] = 8'hca >> { b[11], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$949[1]_new_ , a[11] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$954[1]_new_  = 2'h1 >> a[12];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [12] = 8'hca >> { b[12], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$954[1]_new_ , a[12] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$959[1]_new_  = 2'h1 >> a[13];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [13] = 8'hca >> { b[13], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$959[1]_new_ , a[13] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$964[1]_new_  = 2'h1 >> a[14];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [14] = 8'hca >> { b[14], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$964[1]_new_ , a[14] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$969[1]_new_  = 2'h1 >> a[15];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [15] = 8'hca >> { b[15], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$969[1]_new_ , a[15] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$974[1]_new_  = 2'h1 >> a[16];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [16] = 8'hca >> { b[16], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$974[1]_new_ , a[16] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$979[1]_new_  = 2'h1 >> a[17];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [17] = 8'hca >> { b[17], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$979[1]_new_ , a[17] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$984[1]_new_  = 2'h1 >> a[18];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [18] = 8'hca >> { b[18], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$984[1]_new_ , a[18] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$989[1]_new_  = 2'h1 >> a[19];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [19] = 8'hca >> { b[19], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$989[1]_new_ , a[19] };
  assign \$abc$1209$auto$simplemap.cc:333:simplemap_lut$994[1]_new_  = 2'h1 >> a[20];
  assign \$auto$alumacc.cc:485:replace_alu$3.S [20] = 8'hca >> { b[20], \$abc$1209$auto$simplemap.cc:333:simplemap_lut$994[1]_new_ , a[20] };
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:79.19-85.8" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.final_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [63]),
    .g(1'h0),
    .p(1'h0),
    .sumout(\$abc$1209$abc$385$auto$alumacc.cc:485:replace_alu$3.co )
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[0].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [0]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [1]),
    .g(a[0]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [0]),
    .sumout(sum[0])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[10].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [10]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [11]),
    .g(a[10]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [10]),
    .sumout(sum[10])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[11].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [11]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [12]),
    .g(a[11]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [11]),
    .sumout(sum[11])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[12].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [12]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [13]),
    .g(a[12]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [12]),
    .sumout(sum[12])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[13].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [13]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [14]),
    .g(a[13]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [13]),
    .sumout(sum[13])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[14].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [14]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [15]),
    .g(a[14]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [14]),
    .sumout(sum[14])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[15].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [15]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [16]),
    .g(a[15]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [15]),
    .sumout(sum[15])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[16].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [16]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [17]),
    .g(a[16]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [16]),
    .sumout(sum[16])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[17].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [17]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [18]),
    .g(a[17]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [17]),
    .sumout(sum[17])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[18].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [18]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [19]),
    .g(a[18]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [18]),
    .sumout(sum[18])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[19].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [19]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [20]),
    .g(a[19]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [19]),
    .sumout(sum[19])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[1].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [1]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [2]),
    .g(a[1]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [1]),
    .sumout(sum[1])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[20].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [20]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [21]),
    .g(a[20]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [20]),
    .sumout(sum[20])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[21].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [21]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [22]),
    .g(a[21]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [21]),
    .sumout(sum[21])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[22].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [22]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [23]),
    .g(a[22]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [22]),
    .sumout(sum[22])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[23].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [23]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [24]),
    .g(a[23]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [23]),
    .sumout(sum[23])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[24].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [24]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [25]),
    .g(a[24]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [24]),
    .sumout(sum[24])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[25].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [25]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [26]),
    .g(a[25]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [25]),
    .sumout(sum[25])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[26].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [26]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [27]),
    .g(a[26]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [26]),
    .sumout(sum[26])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[27].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [27]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [28]),
    .g(a[27]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [27]),
    .sumout(sum[27])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[28].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [28]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [29]),
    .g(a[28]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [28]),
    .sumout(sum[28])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[29].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [29]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [30]),
    .g(a[29]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [29]),
    .sumout(sum[29])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[2].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [2]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [3]),
    .g(a[2]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [2]),
    .sumout(sum[2])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[30].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [30]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [31]),
    .g(a[30]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [30]),
    .sumout(sum[30])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[31].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [31]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [32]),
    .g(a[31]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [31]),
    .sumout(sum[31])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[32].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [32]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [33]),
    .g(a[32]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [32]),
    .sumout(sum[32])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[33].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [33]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [34]),
    .g(a[33]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [33]),
    .sumout(sum[33])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[34].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [34]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [35]),
    .g(a[34]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [34]),
    .sumout(sum[34])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[35].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [35]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [36]),
    .g(a[35]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [35]),
    .sumout(sum[35])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[36].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [36]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [37]),
    .g(a[36]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [36]),
    .sumout(sum[36])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[37].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [37]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [38]),
    .g(a[37]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [37]),
    .sumout(sum[37])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[38].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [38]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [39]),
    .g(a[38]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [38]),
    .sumout(sum[38])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[39].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [39]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [40]),
    .g(a[39]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [39]),
    .sumout(sum[39])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[3].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [3]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [4]),
    .g(a[3]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [3]),
    .sumout(sum[3])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[40].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [40]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [41]),
    .g(a[40]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [40]),
    .sumout(sum[40])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[41].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [41]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [42]),
    .g(a[41]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [41]),
    .sumout(sum[41])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[42].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [42]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [43]),
    .g(a[42]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [42]),
    .sumout(sum[42])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[43].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [43]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [44]),
    .g(a[43]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [43]),
    .sumout(sum[43])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[44].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [44]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [45]),
    .g(a[44]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [44]),
    .sumout(sum[44])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[45].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [45]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [46]),
    .g(a[45]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [45]),
    .sumout(sum[45])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[46].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [46]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [47]),
    .g(a[46]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [46]),
    .sumout(sum[46])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[47].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [47]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [48]),
    .g(a[47]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [47]),
    .sumout(sum[47])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[48].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [48]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [49]),
    .g(a[48]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [48]),
    .sumout(sum[48])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[49].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [49]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [50]),
    .g(a[49]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [49]),
    .sumout(sum[49])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[4].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [4]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [5]),
    .g(a[4]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [4]),
    .sumout(sum[4])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[50].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [50]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [51]),
    .g(a[50]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [50]),
    .sumout(sum[50])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[51].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [51]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [52]),
    .g(a[51]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [51]),
    .sumout(sum[51])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[52].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [52]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [53]),
    .g(a[52]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [52]),
    .sumout(sum[52])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[53].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [53]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [54]),
    .g(a[53]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [53]),
    .sumout(sum[53])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[54].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [54]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [55]),
    .g(a[54]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [54]),
    .sumout(sum[54])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[55].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [55]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [56]),
    .g(a[55]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [55]),
    .sumout(sum[55])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[56].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [56]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [57]),
    .g(a[56]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [56]),
    .sumout(sum[56])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[57].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [57]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [58]),
    .g(a[57]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [57]),
    .sumout(sum[57])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[58].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [58]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [59]),
    .g(a[58]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [58]),
    .sumout(sum[58])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[59].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [59]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [60]),
    .g(a[59]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [59]),
    .sumout(sum[59])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[5].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [5]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [6]),
    .g(a[5]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [5]),
    .sumout(sum[5])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[60].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [60]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [61]),
    .g(a[60]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [60]),
    .sumout(sum[60])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[61].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [61]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [62]),
    .g(a[61]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [61]),
    .sumout(sum[61])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[62].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [62]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [63]),
    .g(a[62]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [62]),
    .sumout(sum[62])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[6].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [6]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [7]),
    .g(a[6]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [6]),
    .sumout(sum[6])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[7].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [7]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [8]),
    .g(a[7]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [7]),
    .sumout(sum[7])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[8].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [8]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [9]),
    .g(a[8]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [8]),
    .sumout(sum[8])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:66.16-72.4" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.genblk1.slice[9].genblk1.my_adder  (
    .cin(\$auto$alumacc.cc:485:replace_alu$3.C [9]),
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [10]),
    .g(a[9]),
    .p(\$auto$alumacc.cc:485:replace_alu$3.S [9]),
    .sumout(sum[9])
  );
  (* module_not_derived = 32'h00000001 *)
  (* src = "./rtl/adder_64/adder_64.v:10.22-10.33|/home/users/eda_tools/opensource/yosys_verifc/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/arith_map.v:54.19-60.8" *)
  adder_carry \$auto$alumacc.cc:485:replace_alu$3.intermediate_adder  (
    .cout(\$auto$alumacc.cc:485:replace_alu$3.C [0]),
    .g(cin),
    .p(1'h0)
  );
  assign \$auto$alumacc.cc:485:replace_alu$3.C [65:64] = { 1'h0, cout };
  assign \$auto$alumacc.cc:485:replace_alu$3.S [64] = 1'h0;
endmodule
